/**
 * Офлайн-таблица WMI (первые три символа VIN → марка / завод), 171 (2026-09-25).
 *
 * ЗАЧЕМ: NHTSA vPIC не знает российских сборок (XTA, XW8, Z94, X7L, XWE…) и
 * китайских брендов (LVV, LGW, L6T…) — для рынка РФ это ОСНОВНОЙ бесплатный
 * источник марки. Модель по WMI не определяется никогда (model: null).
 *
 * ИСТОЧНИКИ: список WMI в en.wikipedia.org/wiki/Vehicle_identification_number и
 * таблица «WMI заводов бывшего СССР» в ru.wikipedia.org (wikitext, 2026-09-25),
 * плюс ручные уточнения по рынку РФ/СНГ/Китая. Файл СГЕНЕРИРОВАН скриптом
 * (переопределения в нём же) и затем проверен руками; править можно прямо здесь.
 *
 * ПОЛЯ: make — марка для поля «Марка и модель» (null — завод известен, марка
 * многобрендовая: Автотор, ОАГ, GM); manufacturer / country — для пояснения в
 * notes; ambiguous — другие марки того же завода (UI просит проверить марку).
 */

export interface WmiEntry {
  /** Марка («Lada», «Kia») или null, если по WMI марку назвать нельзя. */
  make: string | null;
  /** Производитель / завод — для пояснения пользователю. */
  manufacturer?: string;
  /** Страна сборки (по-русски). */
  country?: string;
  /** Другие марки, выпускавшиеся под этим WMI, — попросить проверить марку. */
  ambiguous?: string[];
}

export const WMI_TABLE: Readonly<Record<string, WmiEntry>> = {
  // ── Россия, СНГ, Восточная Европа ──
  X0C: { make: null, manufacturer: 'ТагАЗ, Таганрог', country: 'Россия' },
  X1A: {
    make: 'ГАЗ',
    manufacturer: 'ГЗСА / «Бизон», Нижний Новгород (спецавтомобили на шасси ГАЗ)',
    country: 'Россия',
  },
  X1E: { make: 'КАвЗ', manufacturer: 'Курганский автобусный завод', country: 'Россия' },
  X1F: { make: 'НЕФАЗ', manufacturer: 'НЕФАЗ, Нефтекамск', country: 'Россия' },
  X1M: { make: 'ПАЗ', manufacturer: 'Павловский автобусный завод', country: 'Россия' },
  X1P: { make: 'Урал', manufacturer: 'Уральский автомобильный завод, Миасс', country: 'Россия' },
  X1W: { make: 'СЗАП', manufacturer: 'Ставропольский завод автоприцепов', country: 'Россия' },
  X4A: { make: null, manufacturer: 'Автотор, Калининград', country: 'Россия' },
  X4K: { make: 'Volgabus', manufacturer: 'Волжанин / Volgabus, Волжский', country: 'Россия' },
  X4X: { make: 'BMW', manufacturer: 'Автотор, Калининград (сборка BMW)', country: 'Россия' },
  X6D: { make: 'Lada', manufacturer: 'ВАЗинтерСервис, Тольятти', country: 'Россия' },
  X78: { make: 'ГАЗ', manufacturer: 'ГАЗ, Нижний Новгород', country: 'Россия' },
  X7D: { make: 'Lada', manufacturer: 'РосЛада, Сызрань (сборка Lada)', country: 'Россия' },
  X7L: {
    make: 'Renault',
    manufacturer: 'Рено Россия, Москва (Logan, Sandero, Duster, Kaptur, Arkana)',
    country: 'Россия',
  },
  X7M: {
    make: 'Hyundai',
    manufacturer: 'ТагАЗ, Таганрог (Accent, Sonata; также Chery, Vortex, Tagaz)',
    country: 'Россия',
    ambiguous: ['Chery', 'Vortex', 'Tagaz'],
  },
  X7Y: { make: 'Lada', manufacturer: 'Супер-Авто, Тольятти (сборка Lada)', country: 'Россия' },
  X89: { make: null, manufacturer: 'Мелкосерийный производитель (Россия) — см. позиции 12–14 VIN', country: 'Россия' },
  X8U: { make: 'Scania', manufacturer: 'Скания-Питер, Санкт-Петербург', country: 'Россия' },
  X96: { make: 'ГАЗ', manufacturer: 'ГАЗ, Нижний Новгород (ГАЗель, Соболь)', country: 'Россия' },
  X9F: { make: 'Ford', manufacturer: 'Форд Мотор Компани, Всеволожск (Focus, Mondeo)', country: 'Россия' },
  X9L: {
    make: 'Chevrolet',
    manufacturer: 'GM-АвтоВАЗ, Тольятти (Chevrolet Niva → Lada Niva Travel)',
    country: 'Россия',
    ambiguous: ['Lada'],
  },
  X9P: { make: 'Volvo', manufacturer: 'Вольво Восток, Калуга (грузовики)', country: 'Россия' },
  X9X: { make: 'Great Wall', manufacturer: 'Автотрейд-12 / ИМС, Гжель (Hover)', country: 'Россия' },
  XBB: { make: 'Great Wall', manufacturer: 'Great Wall Motors/Litex Motors AD', country: 'Болгария' },
  XLB: { make: 'Volvo', manufacturer: 'Volvo Car B.V./NedCar B.V.', country: 'Нидерланды' },
  XLE: { make: 'Scania', manufacturer: 'Scania Production Zwolle', country: 'Нидерланды' },
  XLR: { make: 'DAF', manufacturer: 'DAF Trucks, Эйндховен', country: 'Нидерланды' },
  XLV: { make: 'DAF', manufacturer: 'DAF Bus', country: 'Нидерланды' },
  XMC: {
    make: 'Mitsubishi',
    manufacturer: 'NedCar, Борн (Colt, Outlander, Carisma; позже MINI, BMW X1)',
    country: 'Нидерланды',
    ambiguous: ['MINI', 'BMW', 'Volvo', 'Smart'],
  },
  XNC: { make: 'Mitsubishi', manufacturer: 'NedCar B.V. Mitsubishi Motors', country: 'Нидерланды' },
  XP7: { make: 'Tesla', manufacturer: 'Tesla Europe', country: 'Нидерланды' },
  XSF: { make: 'БАЗ', manufacturer: 'Брянский автомобильный завод', country: 'Россия' },
  XTA: { make: 'Lada', manufacturer: 'АвтоВАЗ, Тольятти', country: 'Россия' },
  XTB: { make: 'Москвич', manufacturer: 'АЗЛК, Москва', country: 'Россия' },
  XTC: {
    make: 'КАМАЗ',
    manufacturer: 'КАМАЗ, Набережные Челны',
    country: 'Россия',
    ambiguous: ['Москвич (2022+, VIN оформляет КАМАЗ)'],
  },
  XTD: { make: 'ЛуАЗ', manufacturer: 'ЛуАЗ, Луцк', country: 'Украина' },
  XTE: { make: 'ЗАЗ', manufacturer: 'ЗАЗ, Запорожье', country: 'Украина' },
  XTF: { make: 'ГолАЗ', manufacturer: 'Голицынский автобусный завод', country: 'Россия' },
  XTH: { make: 'ГАЗ', manufacturer: 'ГАЗ, Нижний Новгород', country: 'Россия' },
  XTJ: { make: 'СеАЗ', manufacturer: 'СеАЗ, Серпухов (Ока)', country: 'Россия' },
  XTK: { make: 'Иж', manufacturer: 'ИжАвто, Ижевск', country: 'Россия' },
  XTM: { make: 'МАЗ', manufacturer: 'МАЗ, Минск', country: 'Беларусь' },
  XTP: { make: 'ММЗ', manufacturer: 'Мытищинский машиностроительный завод', country: 'Россия' },
  XTT: { make: 'УАЗ', manufacturer: 'УАЗ, Ульяновск', country: 'Россия' },
  XTW: { make: 'ЛАЗ', manufacturer: 'ЛАЗ, Львов', country: 'Украина' },
  XTY: { make: 'ЛиАЗ', manufacturer: 'ЛиАЗ, Ликино-Дулёво', country: 'Россия' },
  XTZ: { make: 'ЗИЛ', manufacturer: 'ЗИЛ, Москва', country: 'Россия' },
  XU1: { make: 'УАЗ', manufacturer: 'УАЗ, Ульяновск (спецавтомобили)', country: 'Россия' },
  XUF: {
    make: 'Chevrolet',
    manufacturer: 'General Motors Auto, Санкт-Петербург (Cruze, Captiva; также Opel Antara)',
    country: 'Россия',
    ambiguous: ['Opel'],
  },
  XUU: { make: 'Chevrolet', manufacturer: 'Автотор, Калининград (Lacetti, Aveo, Epica)', country: 'Россия' },
  XW7: { make: 'Toyota', manufacturer: 'Тойота Мотор, Санкт-Петербург (Camry, RAV4)', country: 'Россия' },
  XW8: {
    make: 'Volkswagen',
    manufacturer: 'Фольксваген Груп Рус, Калуга (Polo, Tiguan; также Škoda Rapid, Octavia)',
    country: 'Россия',
    ambiguous: ['Škoda'],
  },
  XWB: {
    make: 'Chevrolet',
    manufacturer: 'UzAuto Motors, Асака (Nexia, Cobalt, Spark, Damas; ранее Daewoo/Ravon)',
    country: 'Узбекистан',
    ambiguous: ['Daewoo', 'Ravon'],
  },
  XWE: {
    make: 'Kia',
    manufacturer: 'Автотор, Калининград (Rio, Sportage, Cerato, Sorento; также Hyundai)',
    country: 'Россия',
    ambiguous: ['Hyundai'],
  },
  XWF: { make: null, manufacturer: 'Автотор, Калининград', country: 'Россия' },
  XWK: { make: 'Kia', manufacturer: 'ИжАвто, Ижевск (Spectra, Rio, Sorento)', country: 'Россия', ambiguous: ['Иж'] },
  XWW: { make: null, manufacturer: 'Азия Авто, Усть-Каменогорск (Lada, Kia, Škoda, Chevrolet)', country: 'Казахстан' },
  Y3B: { make: 'БелАЗ', manufacturer: 'БелАЗ, Жодино', country: 'Беларусь' },
  Y3K: { make: 'МЗКТ', manufacturer: 'МЗКТ, Минск', country: 'Беларусь' },
  Y3M: { make: 'МАЗ', manufacturer: 'МАЗ, Минск', country: 'Беларусь' },
  Y3N: { make: 'МАЗ', manufacturer: 'МАЗ-MAN, Минск', country: 'Беларусь' },
  Y4K: { make: 'Geely', manufacturer: 'БелДжи, Борисов (Atlas, Coolray, Tugella, Monjaro)', country: 'Беларусь' },
  Y6D: { make: 'ЗАЗ', manufacturer: 'ЗАЗ, Запорожье (Lanos, Sens, Chance, Vida)', country: 'Украина' },
  Y6L: { make: 'Богдан', manufacturer: 'Богдан / ЛуАЗ, Луцк', country: 'Украина' },
  Y6U: { make: 'Škoda', manufacturer: 'Škoda Auto made by Eurocar', country: 'Украина' },
  Y7A: { make: 'КрАЗ', manufacturer: 'КрАЗ, Кременчуг', country: 'Украина' },
  Y7C: { make: 'Great Wall', manufacturer: 'Great Wall Motors KrASZ', country: 'Украина' },
  Y8A: { make: 'ЛАЗ', manufacturer: 'ЛАЗ, Львов', country: 'Украина' },
  Y9Z: {
    make: 'ЗАЗ',
    manufacturer: 'ЗАЗ, Запорожье (сборка Lada, Renault)',
    country: 'Украина',
    ambiguous: ['Lada', 'Renault'],
  },
  YAR: {
    make: 'Toyota',
    manufacturer: 'Toyota Motor Europe used for Toyota ProAce & Toyota ProAce City',
    country: 'Бельгия',
  },
  YB3: { make: 'Volvo', manufacturer: 'Volvo Trucks', country: 'Бельгия' },
  YC1: { make: 'Honda', manufacturer: 'Honda', country: 'Бельгия' },
  YK1: { make: 'Saab', manufacturer: 'Saab built by Valmet Automotive', country: 'Финляндия' },
  YS2: { make: 'Scania', manufacturer: 'Scania, Сёдертелье', country: 'Швеция' },
  YS3: { make: 'Saab', manufacturer: 'Saab Automobile, Тролльхеттан', country: 'Швеция' },
  YS4: { make: 'Scania', manufacturer: 'Scania, Katrineholm bus', country: 'Швеция' },
  YSC: { make: 'Cadillac', manufacturer: 'Cadillac BLS built by Saab', country: 'Швеция' },
  YSM: { make: 'Polestar', manufacturer: 'Polestar', country: 'Швеция' },
  YTN: { make: 'Saab', manufacturer: 'Saab NEVS', country: 'Швеция' },
  YV1: { make: 'Volvo', manufacturer: 'Volvo Cars (легковые)', country: 'Швеция' },
  YV2: { make: 'Volvo', manufacturer: 'Volvo Trucks', country: 'Швеция' },
  YV3: { make: 'Volvo', manufacturer: 'Volvo Buses', country: 'Швеция' },
  YV4: { make: 'Volvo', manufacturer: 'Volvo Cars (SUV)', country: 'Швеция' },
  YV5: { make: 'Volvo', manufacturer: 'Volvo Trucks incomplete vehicle', country: 'Швеция' },
  Z07: { make: 'Volgabus', manufacturer: 'Volgabus, Волжский', country: 'Россия' },
  Z0X: { make: 'Lada', manufacturer: 'Lada Sport, Тольятти', country: 'Россия' },
  Z6F: { make: 'Ford', manufacturer: 'Форд Соллерс, Елабуга (Transit, Kuga, Explorer)', country: 'Россия' },
  Z7G: { make: null, manufacturer: 'Соллерс, Елабуга (Fiat Ducato, Isuzu)', country: 'Россия' },
  Z8N: {
    make: 'Nissan',
    manufacturer: 'Ниссан Мэнуфэкчуринг Рус, Санкт-Петербург (X-Trail, Qashqai, Murano)',
    country: 'Россия',
  },
  Z8T: {
    make: 'Mitsubishi',
    manufacturer: 'ПСМА Рус, Калуга (Outlander, Pajero Sport; также Peugeot 408, Citroën C4)',
    country: 'Россия',
    ambiguous: ['Peugeot', 'Citroën'],
  },
  Z94: {
    make: 'Hyundai',
    manufacturer: 'Хёндэ Мотор Мануфактуринг Рус, Санкт-Петербург (Solaris, Creta; также Kia Rio)',
    country: 'Россия',
    ambiguous: ['Kia'],
  },
  Z9M: {
    make: 'Mercedes-Benz',
    manufacturer: 'Мерседес-Бенц Тракс Восток, Набережные Челны (грузовики)',
    country: 'Россия',
  },
  Z9Z: { make: null, manufacturer: 'Объединённая автомобильная группа (ОАГ), Ижевск', country: 'Россия' },
  ZAA: { make: 'Alfa Romeo', manufacturer: 'Autobianchi', country: 'Италия' },
  ZAC: {
    make: 'Jeep',
    manufacturer: 'FCA Italy, Мельфи (Renegade; также Fiat 500X)',
    country: 'Италия',
    ambiguous: ['Fiat'],
  },
  ZAM: { make: 'Maserati', manufacturer: 'Maserati, Модена', country: 'Италия' },
  ZAR: { make: 'Alfa Romeo', manufacturer: 'Alfa Romeo', country: 'Италия' },
  ZAS: { make: 'Alfa Romeo', manufacturer: 'Alfa Romeo Alfasud & Sprint through 1989', country: 'Италия' },
  ZBA: { make: 'BMW', manufacturer: 'BMW For South africa', country: 'Италия' },
  ZBI: { make: 'BMW', manufacturer: 'BMW For Indonesia', country: 'Италия' },
  ZBM: { make: 'BMW', manufacturer: 'BMW For Philippines', country: 'Италия' },
  ZBP: { make: 'BMW', manufacturer: 'BMW For Malaysia', country: 'Италия' },
  ZBT: { make: 'BMW', manufacturer: 'BMW For Thailand', country: 'Италия' },
  ZC2: { make: 'Chrysler', manufacturer: 'Chrysler TC by Maserati', country: 'Италия' },
  ZCF: { make: 'Iveco', manufacturer: 'Iveco', country: 'Италия' },
  ZDC: { make: 'Honda', manufacturer: 'Honda Italia Industriale S.p.A.', country: 'Италия' },
  ZFA: { make: 'Fiat', manufacturer: 'Fiat (легковые; также Abarth)', country: 'Италия', ambiguous: ['Abarth'] },
  ZFB: { make: 'Fiat', manufacturer: 'Fiat MPV/SUV', country: 'Италия' },
  ZFC: { make: 'Fiat', manufacturer: 'Fiat Professional (Ducato, Doblò)', country: 'Италия' },
  ZFF: { make: 'Ferrari', manufacturer: 'Ferrari, Маранелло', country: 'Италия' },
  ZGA: { make: 'Iveco', manufacturer: 'Iveco Bus', country: 'Италия' },
  ZHW: { make: 'Lamborghini', manufacturer: 'Lamborghini, Сант-Агата-Болоньезе', country: 'Италия' },
  ZK5: { make: 'Hyundai', manufacturer: 'Hyundai Automobili Italia Importazioni', country: 'Италия' },
  ZLA: { make: 'Lancia', manufacturer: 'Lancia', country: 'Италия' },
  ZN3: { make: 'Iveco', manufacturer: 'Iveco Defence', country: 'Италия' },
  ZN6: { make: 'Maserati', manufacturer: 'Maserati (Levante, Grecale)', country: 'Италия' },
  ZPB: { make: 'Lamborghini', manufacturer: 'Lamborghini SUV', country: 'Италия' },
  // ── Китай ──
  HJR: { make: 'Jetour', manufacturer: 'Chery / Jetour (новая серия WMI)', country: 'Китай' },
  L1N: { make: 'Xpeng', manufacturer: 'XPeng Motors', country: 'Китай' },
  L2C: {
    make: 'Jaguar',
    manufacturer: 'Chery Jaguar Land Rover, Чанчжоу',
    country: 'Китай',
    ambiguous: ['Land Rover'],
  },
  L6T: {
    make: 'Geely',
    manufacturer: 'Geely Auto (Coolray, Atlas, Monjaro; также Lynk & Co, Zeekr)',
    country: 'Китай',
    ambiguous: ['Lynk & Co', 'Zeekr'],
  },
  LA6: { make: 'King Long', manufacturer: 'King Long, Сямэнь', country: 'Китай' },
  LB1: { make: 'Mercedes-Benz', manufacturer: 'Fujian Benz (V-Class, Vito)', country: 'Китай' },
  LB3: { make: 'Geely', manufacturer: 'Geely Auto', country: 'Китай' },
  LBE: { make: 'Hyundai', manufacturer: 'Beijing Hyundai', country: 'Китай' },
  LBV: { make: 'BMW', manufacturer: 'BMW Brilliance, Шэньян', country: 'Китай' },
  LC0: { make: 'BYD', manufacturer: 'BYD Auto Industry', country: 'Китай' },
  LCR: { make: 'Gonow', manufacturer: 'Gonow Auto', country: 'Китай' },
  LDC: { make: 'Peugeot', manufacturer: 'Dongfeng Peugeot-Citroën, Ухань', country: 'Китай', ambiguous: ['Citroën'] },
  LDK: { make: 'FAW', manufacturer: 'FAW Bus Co., Ltd.', country: 'Китай' },
  LDN: { make: 'Soueast', manufacturer: 'Soueast Motor, Фучжоу', country: 'Китай' },
  LDY: { make: 'Zhongtong', manufacturer: 'Zhongtong Bus', country: 'Китай' },
  LE4: { make: 'Mercedes-Benz', manufacturer: 'Beijing Benz, Пекин', country: 'Китай' },
  LEF: { make: 'JMC', manufacturer: 'Jiangling Motors, Наньчан', country: 'Китай' },
  LET: { make: 'Isuzu', manufacturer: 'Jiangxi Isuzu', country: 'Китай' },
  LFA: { make: 'Ford', manufacturer: 'Ford Lio Ho Motor Co Ltd old designation', country: 'Китай' },
  LFB: { make: 'FAW', manufacturer: 'FAW Jilin (Bestune)', country: 'Китай', ambiguous: ['Bestune'] },
  LFM: { make: 'Toyota', manufacturer: 'FAW Toyota', country: 'Китай' },
  LFN: { make: 'FAW', manufacturer: 'FAW Bus Co., Ltd.', country: 'Китай' },
  LFP: {
    make: 'FAW',
    manufacturer: 'FAW Car (Bestune; также Hongqi)',
    country: 'Китай',
    ambiguous: ['Hongqi', 'Bestune'],
  },
  LFV: {
    make: 'Volkswagen',
    manufacturer: 'FAW-Volkswagen, Чанчунь (также Audi, Jetta)',
    country: 'Китай',
    ambiguous: ['Audi'],
  },
  LGA: { make: 'Dongfeng', manufacturer: 'Dongfeng Commercial Vehicle (грузовики)', country: 'Китай' },
  LGB: { make: 'Nissan', manufacturer: 'Dongfeng Nissan', country: 'Китай' },
  LGC: { make: 'Dongfeng', manufacturer: 'Dongfeng Commercial Vehicle Co., Ltd. buses', country: 'Китай' },
  LGG: {
    make: 'Dongfeng',
    manufacturer: 'Dongfeng Liuzhou Motor (Forthing)',
    country: 'Китай',
    ambiguous: ['Forthing'],
  },
  LGJ: { make: 'Dongfeng', manufacturer: 'Dongfeng Fengshen (Aeolus)', country: 'Китай' },
  LGL: { make: 'Daewoo', manufacturer: 'Guilin Daewoo', country: 'Китай' },
  LGW: {
    make: 'Haval',
    manufacturer: 'Great Wall Motor, Баодин (Haval, Tank, GWM Poer, Wey)',
    country: 'Китай',
    ambiguous: ['Tank', 'Great Wall', 'Wey'],
  },
  LGX: { make: 'BYD', manufacturer: 'BYD Auto', country: 'Китай' },
  LH1: { make: 'Haima', manufacturer: 'FAW Haima, Хайкоу', country: 'Китай' },
  LHG: { make: 'Honda', manufacturer: 'Guangqi Honda, Гуанчжоу', country: 'Китай' },
  LJ1: { make: 'JAC', manufacturer: 'JAC Motors, Хэфэй', country: 'Китай' },
  LJ8: { make: 'Zotye', manufacturer: 'Zotye Auto', country: 'Китай' },
  LJD: { make: 'Kia', manufacturer: 'Dongfeng Yueda Kia, Яньчэн', country: 'Китай' },
  LJN: { make: 'Nissan', manufacturer: 'Zhengzhou Nissan', country: 'Китай' },
  LJX: { make: 'Ford', manufacturer: 'JMC Ford', country: 'Китай' },
  LKC: { make: 'Changhe', manufacturer: 'Changhe Automobile', country: 'Китай' },
  LKG: { make: 'Lotus', manufacturer: 'Youngman Lotus Automobile Co., Ltd.', country: 'Китай' },
  LKL: { make: 'Higer', manufacturer: 'Higer Bus, Сучжоу', country: 'Китай' },
  LKT: { make: 'Lifan', manufacturer: 'Yunnan Lifan Junma Vehicle Co., Ltd. commercial vehicles', country: 'Китай' },
  LL3: { make: 'Golden Dragon', manufacturer: 'Xiamen Golden Dragon Bus', country: 'Китай' },
  LL6: { make: 'Mitsubishi', manufacturer: 'GAC Mitsubishi, Чанша', country: 'Китай' },
  LLN: { make: 'Qoros', manufacturer: 'Qoros Auto', country: 'Китай' },
  LLV: { make: 'Lifan', manufacturer: 'Lifan Motors, Чунцин', country: 'Китай' },
  LM6: { make: 'SWM', manufacturer: 'SWM Motors (Brilliance Shineray)', country: 'Китай' },
  LMG: { make: 'GAC', manufacturer: 'GAC Trumpchi (GS8, GN8, Empow)', country: 'Китай' },
  LNB: { make: 'BAIC', manufacturer: 'BAIC Motor, Пекин', country: 'Китай' },
  LNP: { make: 'MG', manufacturer: 'NAC MG / Nanjing Fiat', country: 'Китай', ambiguous: ['Fiat'] },
  LNY: { make: 'Yuejin', manufacturer: 'Nanjing Yuejin (SAIC)', country: 'Китай' },
  LPA: { make: 'DS', manufacturer: 'Changan PSA, Шэньчжэнь', country: 'Китай' },
  LPE: { make: 'BYD', manufacturer: 'BYD Auto', country: 'Китай' },
  LPS: { make: 'Polestar', manufacturer: 'Polestar, Чэнду', country: 'Китай' },
  LRB: { make: 'Buick', manufacturer: 'SAIC General Motors, Шанхай', country: 'Китай' },
  LRD: { make: 'Foton', manufacturer: 'Beijing Foton Daimler (Auman)', country: 'Китай' },
  LRE: { make: 'Cadillac', manufacturer: 'SAIC General Motors, Шанхай', country: 'Китай' },
  LRW: { make: 'Tesla', manufacturer: 'Tesla, Шанхай (Gigafactory 3)', country: 'Китай' },
  LS4: { make: 'Changan', manufacturer: 'Changan Automobile (CS35, CS55, CS75, UNI-K)', country: 'Китай' },
  LS5: {
    make: 'Changan',
    manufacturer: 'Changan Automobile (также Changan Suzuki)',
    country: 'Китай',
    ambiguous: ['Suzuki'],
  },
  LSF: { make: 'Maxus', manufacturer: 'SAIC Maxus', country: 'Китай' },
  LSG: { make: 'Chevrolet', manufacturer: 'SAIC General Motors, Шанхай', country: 'Китай' },
  LSH: { make: 'Maxus', manufacturer: 'SAIC Maxus', country: 'Китай' },
  LSJ: { make: 'MG', manufacturer: 'SAIC Motor (MG, Roewe)', country: 'Китай', ambiguous: ['Roewe'] },
  LSK: { make: 'Maxus', manufacturer: 'SAIC Maxus', country: 'Китай' },
  LSV: {
    make: 'Volkswagen',
    manufacturer: 'SAIC Volkswagen, Шанхай (также Škoda)',
    country: 'Китай',
    ambiguous: ['Škoda'],
  },
  LSY: {
    make: 'Brilliance',
    manufacturer: 'Brilliance Auto / Jinbei, Шэньян',
    country: 'Китай',
    ambiguous: ['Jinbei'],
  },
  LTA: { make: 'ZX Auto', manufacturer: 'Zhongxing Auto', country: 'Китай' },
  LTN: { make: 'Chrysler', manufacturer: 'Soueast built Chrysler & Dodge vehicles', country: 'Китай' },
  LTV: { make: 'Toyota', manufacturer: 'FAW Toyota, Тяньцзинь', country: 'Китай' },
  LUC: { make: 'Honda', manufacturer: 'Honda Automobile (China)', country: 'Китай' },
  LUD: { make: 'Dongfeng', manufacturer: 'Dongfeng Nissan Diesel Motor Co Ltd', country: 'Китай' },
  LUX: { make: 'Dongfeng', manufacturer: 'Dongfeng Yulon Motor Co. Ltd', country: 'Китай' },
  LVF: { make: 'Suzuki', manufacturer: 'Changhe Suzuki', country: 'Китай' },
  LVG: { make: 'Toyota', manufacturer: 'GAC Toyota, Гуанчжоу', country: 'Китай' },
  LVH: { make: 'Honda', manufacturer: 'Dongfeng Honda, Ухань', country: 'Китай' },
  LVM: { make: 'Chery', manufacturer: 'Chery Commercial Vehicle (Karry)', country: 'Китай', ambiguous: ['Karry'] },
  LVR: { make: 'Mazda', manufacturer: 'Changan Mazda, Нанкин', country: 'Китай' },
  LVS: { make: 'Ford', manufacturer: 'Changan Ford, Чунцин (также Mazda)', country: 'Китай', ambiguous: ['Mazda'] },
  LVT: {
    make: 'Chery',
    manufacturer: 'Chery Automobile (Exeed, Jetour)',
    country: 'Китай',
    ambiguous: ['Exeed', 'Jetour'],
  },
  LVU: { make: 'Jetour', manufacturer: 'Chery / Jetour', country: 'Китай' },
  LVV: {
    make: 'Chery',
    manufacturer: 'Chery Automobile, Уху (Tiggo; также Omoda, Jaecoo)',
    country: 'Китай',
    ambiguous: ['Omoda', 'Jaecoo'],
  },
  LVX: { make: 'Landwind', manufacturer: 'Jiangling Landwind', country: 'Китай' },
  LVY: { make: 'Volvo', manufacturer: 'Volvo Cars, Дацин', country: 'Китай' },
  LVZ: { make: 'DFSK', manufacturer: 'DFSK Motor (Dongfeng Sokon)', country: 'Китай' },
  LWL: { make: 'Isuzu', manufacturer: 'Qingling Isuzu, Чунцин', country: 'Китай' },
  LWV: { make: 'Jeep', manufacturer: 'GAC Fiat Chrysler, Чанша', country: 'Китай', ambiguous: ['Fiat'] },
  LXV: { make: 'Borgward', manufacturer: 'Beijing Borgward', country: 'Китай' },
  LYV: { make: 'Volvo', manufacturer: 'Volvo Cars, Чэнду / Лунцяо', country: 'Китай' },
  LZF: { make: 'Hongyan', manufacturer: 'SAIC Iveco Hongyan', country: 'Китай', ambiguous: ['Iveco'] },
  LZG: { make: 'Shacman', manufacturer: 'Shaanxi Automobile Group', country: 'Китай' },
  LZU: { make: 'Isuzu', manufacturer: 'Guangzhou Isuzu Bus', country: 'Китай' },
  LZW: {
    make: 'Wuling',
    manufacturer: 'SAIC-GM-Wuling, Лючжоу (также Baojun)',
    country: 'Китай',
    ambiguous: ['Baojun'],
  },
  LZY: { make: 'Yutong', manufacturer: 'Yutong Bus, Чжэнчжоу', country: 'Китай' },
  LZZ: {
    make: 'Sinotruk',
    manufacturer: 'Sinotruk / CNHTC (Howo, Sitrak)',
    country: 'Китай',
    ambiguous: ['Howo', 'Sitrak'],
  },
  // ── Япония и Корея ──
  J81: { make: 'Chevrolet', manufacturer: 'Chevrolet/Geo car made by Isuzu', country: 'Япония' },
  J87: { make: 'Pontiac', manufacturer: 'Pontiac/Asüna car made by Isuzu for GM Canada', country: 'Япония' },
  J8Z: { make: 'Chevrolet', manufacturer: 'Chevrolet pickup truck made by Isuzu', country: 'Япония' },
  JA3: { make: 'Mitsubishi', manufacturer: 'Mitsubishi car', country: 'Япония' },
  JA4: { make: 'Mitsubishi', manufacturer: 'Mitsubishi MPV/SUV', country: 'Япония' },
  JA7: { make: 'Mitsubishi', manufacturer: 'Mitsubishi truck', country: 'Япония' },
  JAA: { make: 'Isuzu', manufacturer: 'Isuzu truck', country: 'Япония' },
  JAB: { make: 'Isuzu', manufacturer: 'Isuzu car', country: 'Япония' },
  JAC: { make: 'Isuzu', manufacturer: 'Isuzu SUV', country: 'Япония' },
  JAE: { make: 'Acura', manufacturer: 'Acura SLX made by Isuzu', country: 'Япония' },
  JAL: {
    make: 'Isuzu',
    manufacturer: 'Isuzu commercial trucks & Chevrolet commercial trucks made by Isuzu 2016+ & Hino',
    country: 'Япония',
  },
  JAM: { make: 'Isuzu', manufacturer: 'Isuzu commercial trucks', country: 'Япония' },
  JB3: { make: 'Dodge', manufacturer: 'Dodge car made by Mitsubishi Motors', country: 'Япония' },
  JB4: { make: 'Dodge', manufacturer: 'Dodge MPV/SUV made by Mitsubishi Motors', country: 'Япония' },
  JB7: { make: 'Dodge', manufacturer: 'Dodge truck made by Mitsubishi Motors', country: 'Япония' },
  JC0: { make: 'Ford', manufacturer: 'Ford brand cars made by Mazda', country: 'Япония' },
  JC1: { make: 'Fiat', manufacturer: 'Fiat 124 Spider made by Mazda', country: 'Япония' },
  JC2: { make: 'Ford', manufacturer: 'Ford Courier made by Mazda', country: 'Япония' },
  JD1: { make: 'Daihatsu', manufacturer: 'Daihatsu car', country: 'Япония' },
  JD2: { make: 'Daihatsu', manufacturer: 'Daihatsu SUV', country: 'Япония' },
  JD4: { make: 'Daihatsu', manufacturer: 'Daihatsu truck', country: 'Япония' },
  JDA: { make: 'Daihatsu', manufacturer: 'Daihatsu', country: 'Япония' },
  JE3: { make: 'Mitsubishi', manufacturer: 'Eagle car made by Mitsubishi Motors', country: 'Япония' },
  JE4: { make: 'Mitsubishi', manufacturer: 'Mitsubishi', country: 'Япония' },
  JF1: { make: 'Subaru', manufacturer: 'Subaru – Fuji Heavy Industries car', country: 'Япония' },
  JF2: { make: 'Subaru', manufacturer: 'Subaru – Fuji Heavy Industries SUV', country: 'Япония' },
  JF3: { make: 'Subaru', manufacturer: 'Subaru – Fuji Heavy Industries truck', country: 'Япония' },
  JF4: { make: 'Saab', manufacturer: 'Saab 9-2X made by Subaru', country: 'Япония' },
  JG1: { make: 'Chevrolet', manufacturer: 'Chevrolet/Geo car made by Suzuki', country: 'Япония' },
  JG7: { make: 'Pontiac', manufacturer: 'Pontiac/Asuna car made by Suzuki for GM Canada', country: 'Япония' },
  JGC: { make: 'Chevrolet', manufacturer: 'Chevrolet/Geo SUV made by Suzuki', country: 'Япония' },
  JGT: { make: 'GMC', manufacturer: 'GMC SUV made by Suzuki for GM Canada', country: 'Япония' },
  JH4: { make: 'Acura', manufacturer: 'Acura car', country: 'Япония' },
  JHD: { make: 'Hino', manufacturer: 'Hino Motors', country: 'Япония' },
  JHF: { make: 'Hino', manufacturer: 'Hino Motors', country: 'Япония' },
  JHL: { make: 'Honda', manufacturer: 'Honda MPV/SUV', country: 'Япония' },
  JHM: { make: 'Honda', manufacturer: 'Honda car', country: 'Япония' },
  JJ3: { make: 'Chrysler', manufacturer: 'Chrysler car made by Mitsubishi Motors', country: 'Япония' },
  JLF: { make: 'Mitsubishi', manufacturer: 'Mitsubishi FUSO Truck & Bus Corp', country: 'Япония' },
  JLS: {
    make: 'Mitsubishi',
    manufacturer: 'Sterling Trucks 360 made by Mitsubishi FUSO Truck & Bus Corp',
    country: 'Япония',
  },
  JM0: { make: 'Mazda', manufacturer: 'Mazda for Oceania export', country: 'Япония' },
  JM1: { make: 'Mazda', manufacturer: 'Mazda car', country: 'Япония' },
  JM2: { make: 'Mazda', manufacturer: 'Mazda truck', country: 'Япония' },
  JM3: { make: 'Mazda', manufacturer: 'Mazda MPV/SUV', country: 'Япония' },
  JM6: { make: 'Mazda', manufacturer: 'Mazda', country: 'Япония' },
  JM7: { make: 'Mazda', manufacturer: 'Mazda', country: 'Япония' },
  JMB: { make: 'Mitsubishi', manufacturer: 'Mitsubishi Motors', country: 'Япония' },
  JMF: { make: 'Mitsubishi', manufacturer: 'Mitsubishi', country: 'Япония' },
  JMY: { make: 'Mitsubishi', manufacturer: 'Mitsubishi', country: 'Япония' },
  JMZ: { make: 'Mazda', manufacturer: 'Mazda for Europe export', country: 'Япония' },
  JN1: {
    make: 'Nissan',
    manufacturer: 'Nissan Motor (легковые; также Infiniti)',
    country: 'Япония',
    ambiguous: ['Infiniti'],
  },
  JN3: { make: 'Nissan', manufacturer: 'Nissan incomplete vehicle', country: 'Япония' },
  JN6: { make: 'Nissan', manufacturer: 'Nissan truck', country: 'Япония' },
  JN8: {
    make: 'Nissan',
    manufacturer: 'Nissan Motor (SUV; также Infiniti)',
    country: 'Япония',
    ambiguous: ['Infiniti'],
  },
  JNA: { make: 'Nissan', manufacturer: 'Nissan Diesel/UD Trucks incomplete vehicle', country: 'Япония' },
  JNC: { make: 'Nissan', manufacturer: 'Nissan Diesel/UD Trucks', country: 'Япония' },
  JNE: { make: 'Nissan', manufacturer: 'Nissan Diesel/UD Trucks truck', country: 'Япония' },
  JNK: { make: 'Infiniti', manufacturer: 'Infiniti car', country: 'Япония' },
  JNR: { make: 'Infiniti', manufacturer: 'Infiniti SUV', country: 'Япония' },
  JNX: { make: 'Infiniti', manufacturer: 'Infiniti incomplete vehicle', country: 'Япония' },
  JP3: { make: 'Plymouth', manufacturer: 'Plymouth car made by Mitsubishi Motors', country: 'Япония' },
  JP4: { make: 'Plymouth', manufacturer: 'Plymouth MPV/SUV made by Mitsubishi Motors', country: 'Япония' },
  JP7: { make: 'Plymouth', manufacturer: 'Plymouth truck made by Mitsubishi Motors', country: 'Япония' },
  JPC: { make: 'Nissan', manufacturer: 'Nissan Diesel/UD Trucks', country: 'Япония' },
  JR2: { make: 'Isuzu', manufacturer: 'Isuzu Oasis made by Honda', country: 'Япония' },
  JS2: { make: 'Suzuki', manufacturer: 'Suzuki car', country: 'Япония' },
  JS3: { make: 'Suzuki', manufacturer: 'Suzuki SUV', country: 'Япония' },
  JSA: { make: 'Suzuki', manufacturer: 'Suzuki Motor (Grand Vitara, SX4, Jimny)', country: 'Япония' },
  JT2: { make: 'Toyota', manufacturer: 'Toyota car', country: 'Япония' },
  JT3: { make: 'Toyota', manufacturer: 'Toyota MPV/SUV', country: 'Япония' },
  JT4: { make: 'Toyota', manufacturer: 'Toyota truck', country: 'Япония' },
  JT5: { make: 'Toyota', manufacturer: 'Toyota incomplete vehicle', country: 'Япония' },
  JT6: { make: 'Lexus', manufacturer: 'Lexus SUV', country: 'Япония' },
  JT8: { make: 'Lexus', manufacturer: 'Lexus car', country: 'Япония' },
  JTD: { make: 'Toyota', manufacturer: 'Toyota car', country: 'Япония' },
  JTE: { make: 'Toyota', manufacturer: 'Toyota MPV/SUV', country: 'Япония' },
  JTF: { make: 'Toyota', manufacturer: 'Toyota van/truck', country: 'Япония' },
  JTG: { make: 'Toyota', manufacturer: 'Toyota MPV/bus', country: 'Япония' },
  JTH: { make: 'Lexus', manufacturer: 'Lexus car', country: 'Япония' },
  JTJ: { make: 'Lexus', manufacturer: 'Lexus SUV', country: 'Япония' },
  JTK: { make: 'Toyota', manufacturer: 'Toyota car', country: 'Япония' },
  JTL: { make: 'Toyota', manufacturer: 'Toyota SUV', country: 'Япония' },
  JTM: { make: 'Toyota', manufacturer: 'Toyota SUV', country: 'Япония' },
  JTN: { make: 'Toyota', manufacturer: 'Toyota car', country: 'Япония' },
  JW6: { make: 'Mitsubishi', manufacturer: 'Mitsubishi FUSO division of Mitsubishi Motors', country: 'Япония' },
  KL1: { make: 'Chevrolet', manufacturer: 'GM Korea (Daewoo), Инчхон', country: 'Южная Корея', ambiguous: ['Daewoo'] },
  KL2: { make: 'Daewoo', manufacturer: 'Daewoo/GM Daewoo Pontiac', country: 'Южная Корея' },
  KL3: { make: 'Chevrolet', manufacturer: 'GM Korea (Holden)', country: 'Южная Корея', ambiguous: ['Holden'] },
  KL4: { make: 'Buick', manufacturer: 'GM Korea Buick', country: 'Южная Корея' },
  KL5: { make: 'Daewoo', manufacturer: 'GM Daewoo Suzuki', country: 'Южная Корея' },
  KL6: { make: 'Daewoo', manufacturer: 'GM Daewoo GMC', country: 'Южная Корея' },
  KL7: { make: 'Chevrolet', manufacturer: 'GM Korea (SUV / минивэны)', country: 'Южная Корея' },
  KL8: { make: 'Chevrolet', manufacturer: 'GM Korea (Spark)', country: 'Южная Корея' },
  KLA: { make: 'Daewoo', manufacturer: 'GM Korea (Daewoo)', country: 'Южная Корея', ambiguous: ['Chevrolet'] },
  KM8: { make: 'Hyundai', manufacturer: 'Hyundai Motor (SUV)', country: 'Южная Корея' },
  KM9: { make: 'SsangYong', manufacturer: 'Edison Motors/KG Mobility Commercial Buses', country: 'Южная Корея' },
  KME: { make: 'Hyundai', manufacturer: 'Hyundai Motor (грузовики)', country: 'Южная Корея' },
  KMF: { make: 'Hyundai', manufacturer: 'Hyundai Motor (вэны, грузовики)', country: 'Южная Корея' },
  KMH: { make: 'Hyundai', manufacturer: 'Hyundai Motor (легковые)', country: 'Южная Корея' },
  KMJ: { make: 'Hyundai', manufacturer: 'Hyundai Motor (автобусы)', country: 'Южная Корея' },
  KMT: { make: 'Genesis', manufacturer: 'Genesis Motor (легковые)', country: 'Южная Корея' },
  KMU: { make: 'Genesis', manufacturer: 'Genesis Motor (SUV)', country: 'Южная Корея' },
  KNA: { make: 'Kia', manufacturer: 'Kia (легковые)', country: 'Южная Корея' },
  KNC: { make: 'Kia', manufacturer: 'Kia (коммерческие)', country: 'Южная Корея' },
  KND: { make: 'Kia', manufacturer: 'Kia (SUV / минивэны)', country: 'Южная Корея' },
  KNE: { make: 'Kia', manufacturer: 'Kia (экспортные)', country: 'Южная Корея' },
  KNG: { make: 'Kia', manufacturer: 'Kia Granbird', country: 'Южная Корея' },
  KNH: { make: 'Kia', manufacturer: 'Kia (минивэны)', country: 'Южная Корея' },
  KNJ: { make: 'Ford', manufacturer: 'Ford Festiva & Aspire', country: 'Южная Корея' },
  KNM: {
    make: 'Renault',
    manufacturer: 'Renault Samsung Motors, Пусан',
    country: 'Южная Корея',
    ambiguous: ['Samsung', 'Nissan'],
  },
  KPA: {
    make: 'SsangYong',
    manufacturer: 'SsangYong / KG Mobility (пикапы)',
    country: 'Южная Корея',
    ambiguous: ['KGM'],
  },
  KPB: {
    make: 'SsangYong',
    manufacturer: 'SsangYong / KG Mobility (легковые)',
    country: 'Южная Корея',
    ambiguous: ['KGM'],
  },
  KPH: { make: 'Mitsubishi', manufacturer: 'Mitsubishi Precis', country: 'Южная Корея' },
  KPT: { make: 'SsangYong', manufacturer: 'SsangYong / KG Mobility (SUV)', country: 'Южная Корея', ambiguous: ['KGM'] },
  // ── Европа, Азия, Африка ──
  M3G: { make: 'Isuzu', manufacturer: 'Isuzu Motors India' },
  MA1: { make: 'Mahindra', manufacturer: 'Mahindra & Mahindra', country: 'Индия' },
  MA3: { make: 'Suzuki', manufacturer: 'Maruti Suzuki India', country: 'Индия', ambiguous: ['Maruti'] },
  MA7: {
    make: 'Mitsubishi',
    manufacturer: 'Hindustan Motors Ltd & Mitsubishi Motors models made by Hindustan Motors & Isuzu',
    country: 'Индия',
  },
  MAH: { make: 'Fiat', manufacturer: 'Fiat India Automobiles Pvt. Ltd', country: 'Индия' },
  MAJ: { make: 'Ford', manufacturer: 'Ford India', country: 'Индия' },
  MAK: { make: 'Honda', manufacturer: 'Honda Cars India', country: 'Индия' },
  MAL: { make: 'Hyundai', manufacturer: 'Hyundai Motor India, Ченнаи (i10, i20, Creta)', country: 'Индия' },
  MAT: { make: 'Tata', manufacturer: 'Tata Motors', country: 'Индия' },
  MBH: { make: 'Nissan', manufacturer: 'Nissan Pixo made by Maruti Suzuki India Limited', country: 'Индия' },
  MBJ: { make: 'Toyota', manufacturer: 'Toyota Kirloskar Motor', country: 'Индия' },
  MBK: { make: 'MAN', manufacturer: 'MAN Trucks India Pvt. Ltd', country: 'Индия' },
  MCD: { make: 'Mahindra', manufacturer: 'Mahindra Two Wheelers', country: 'Индия' },
  MDH: { make: 'Nissan', manufacturer: 'Nissan Motor India Pvt Ltd', country: 'Индия' },
  MEC: {
    make: 'Mercedes-Benz',
    manufacturer: 'Daimler India Commercial Vehicles Pvt. Ltd. BharatBenz',
    country: 'Индия',
  },
  MEE: { make: 'Renault', manufacturer: 'Renault India, Ченнаи (Duster, Kwid)', country: 'Индия' },
  MEX: { make: 'Volkswagen', manufacturer: 'Volkswagen India, Пуна (Polo, Vento)', country: 'Индия' },
  MH1: { make: 'Honda', manufacturer: 'PT Astra Honda Motor', country: 'Индонезия' },
  MHF: { make: 'Toyota', manufacturer: 'Toyota Motor Manufacturing Indonesia (Fortuner, Rush)', country: 'Индонезия' },
  MHH: { make: 'BMW', manufacturer: 'BMW cars 2003-2019 India', country: 'Индонезия' },
  MHK: { make: 'Daihatsu', manufacturer: 'Astra Daihatsu Motor', country: 'Индонезия' },
  MHL: { make: 'Mercedes-Benz', manufacturer: 'PT Mercedes-Benz Indonesia', country: 'Индонезия' },
  MHR: { make: 'Honda', manufacturer: 'Honda Prospect Motor', country: 'Индонезия' },
  MHY: { make: 'Suzuki', manufacturer: 'Suzuki Indomobil Motor (Ertiga)', country: 'Индонезия' },
  MK2: { make: 'Mitsubishi', manufacturer: 'Mitsubishi Motors Krama Yudha Indonesia (Xpander)', country: 'Индонезия' },
  ML3: { make: 'Mitsubishi', manufacturer: 'Mitsubishi Motors', country: 'Таиланд' },
  MLC: { make: 'Suzuki', manufacturer: 'Thai Suzuki Motor Co., Ltd.', country: 'Таиланд' },
  MM8: { make: 'Mazda', manufacturer: 'Mazda / AutoAlliance Thailand', country: 'Таиланд' },
  MMF: { make: 'BMW', manufacturer: 'BMW', country: 'Таиланд' },
  MMH: { make: 'Tata', manufacturer: 'Tata', country: 'Таиланд' },
  MMK: { make: 'Toyota', manufacturer: 'Toyota', country: 'Таиланд' },
  MML: { make: 'MG', manufacturer: 'MG', country: 'Таиланд' },
  MMM: { make: 'Chevrolet', manufacturer: 'Chevrolet', country: 'Таиланд' },
  MMR: { make: 'Subaru', manufacturer: 'Subaru', country: 'Таиланд' },
  MMS: { make: 'Suzuki', manufacturer: 'Suzuki', country: 'Таиланд' },
  MMT: { make: 'Mitsubishi', manufacturer: 'Mitsubishi Motors Thailand (Pajero Sport, L200)', country: 'Таиланд' },
  MMU: { make: 'Holden', manufacturer: 'Holden', country: 'Таиланд' },
  MNA: { make: 'Ford', manufacturer: 'Ford Thailand (Ranger)', country: 'Таиланд' },
  MNB: { make: 'Ford', manufacturer: 'Ford Thailand (Ranger, Everest)', country: 'Таиланд' },
  MNC: { make: 'Ford', manufacturer: 'Ford for left-hand drive markets', country: 'Таиланд' },
  MNK: { make: 'Hino', manufacturer: 'Hino Motors Manufacturing Thailand Co Ltd', country: 'Таиланд' },
  MNT: { make: 'Nissan', manufacturer: 'Nissan Motor Thailand', country: 'Таиланд' },
  MP1: { make: 'Isuzu', manufacturer: 'Isuzu Motors Thailand (D-Max, MU-X)', country: 'Таиланд' },
  MP2: { make: 'Mazda', manufacturer: 'Mazda BT-50 pickup built by Isuzu Motors Co., Ltd.', country: 'Таиланд' },
  MP5: { make: 'Foton', manufacturer: 'Foton', country: 'Таиланд' },
  MPA: { make: 'Isuzu', manufacturer: 'Isuzu Motors Thailand', country: 'Таиланд' },
  MPB: { make: 'Ford', manufacturer: 'Ford', country: 'Таиланд' },
  MR0: { make: 'Toyota', manufacturer: 'Toyota Motor Thailand (Hilux, Fortuner)', country: 'Таиланд' },
  MR1: { make: 'Toyota', manufacturer: 'Toyota', country: 'Таиланд' },
  MR2: { make: 'Toyota', manufacturer: 'Toyota', country: 'Таиланд' },
  MRH: { make: 'Honda', manufacturer: 'Honda Automobile Thailand', country: 'Таиланд' },
  MS0: { make: 'Kia', manufacturer: 'SSS MOTORS Myanmar/Kia', country: 'Мьянма' },
  MS3: { make: 'Suzuki', manufacturer: 'Suzuki Myanmar Motor Co., Ltd.', country: 'Мьянма' },
  MX0: { make: null, manufacturer: 'АгромашХолдинг, Костанай', country: 'Казахстан' },
  MX1: { make: null, manufacturer: 'СарыАркаАвтоПром, Костанай (Hyundai, JAC, Chevrolet)', country: 'Казахстан' },
  MX3: { make: 'Hyundai', manufacturer: 'Hyundai Trans Auto', country: 'Казахстан' },
  MZ7: { make: 'MG', manufacturer: 'MG Motor India Pvt. Ltd.' },
  MZB: { make: 'Kia', manufacturer: 'Kia India, Анантапур (Seltos, Sonet)', country: 'Индия' },
  NAA: { make: 'Iran Khodro', manufacturer: 'Iran Khodro (Samand)', country: 'Иран' },
  NAD: { make: 'Saipa', manufacturer: 'Saipa Diesel', country: 'Иран' },
  NAP: { make: 'Iran Khodro', manufacturer: 'Pars Khodro', country: 'Иран' },
  NAS: { make: 'Saipa', manufacturer: 'Saipa Co.', country: 'Иран' },
  NC0: { make: 'BMW', manufacturer: 'BMW South Africa', country: 'Иран' },
  NFB: { make: 'Honda', manufacturer: 'Honda Atlas Cars Pakistan Ltd', country: 'Пакистан' },
  NLA: { make: 'Honda', manufacturer: 'Honda Türkiye, Гебзе (Civic)', country: 'Турция' },
  NLH: { make: 'Hyundai', manufacturer: 'Hyundai Assan, Измит (i20, i10)', country: 'Турция' },
  NLJ: { make: 'Hyundai', manufacturer: 'Hyundai Assan Otomotiv van', country: 'Турция' },
  NM0: { make: 'Ford', manufacturer: 'Ford Otosan, Коджаэли (Transit, Tourneo)', country: 'Турция' },
  NM1: { make: 'Renault', manufacturer: 'Oyak-Renault Oto Fab AS', country: 'Турция' },
  NM4: { make: 'Fiat', manufacturer: 'Tofaş, Бурса (Doblo, Egea/Tipo)', country: 'Турция' },
  NMA: { make: 'MAN', manufacturer: 'MAN Türkiye A.Ş.', country: 'Турция' },
  NMB: { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz Türk (автобусы, грузовики)', country: 'Турция' },
  NMT: {
    make: 'Toyota',
    manufacturer: 'Toyota Motor Manufacturing Turkey, Сакарья (Corolla, C-HR)',
    country: 'Турция',
  },
  NNA: { make: 'Isuzu', manufacturer: 'Anadolu Isuzu', country: 'Турция' },
  PAB: { make: 'Isuzu', manufacturer: 'Isuzu Philippines Corporation', country: 'Филиппины' },
  PAD: { make: 'Honda', manufacturer: 'Honda Cars Philippines', country: 'Филиппины' },
  PAF: { make: 'BMW', manufacturer: 'BMW Philippines', country: 'Филиппины' },
  PE1: { make: 'Ford', manufacturer: 'Ford Motor Company Philippines', country: 'Филиппины' },
  PE3: {
    make: 'Mazda',
    manufacturer: 'Mazda Philippines made by Ford Motor Company Philippines',
    country: 'Филиппины',
  },
  PL1: { make: 'Proton', manufacturer: 'Proton', country: 'Малайзия' },
  PL8: { make: 'Hyundai', manufacturer: 'Hyundai/Inokom', country: 'Малайзия' },
  PLP: { make: 'Subaru', manufacturer: 'Subaru', country: 'Малайзия' },
  PLZ: { make: 'Isuzu', manufacturer: 'Isuzu Malaysia', country: 'Малайзия' },
  PM1: { make: 'BMW', manufacturer: 'BMW', country: 'Малайзия' },
  PM2: { make: 'Perodua', manufacturer: 'Perodua', country: 'Малайзия' },
  PMH: { make: 'Honda', manufacturer: 'Honda car', country: 'Малайзия' },
  PN8: { make: 'Nissan', manufacturer: 'Nissan', country: 'Малайзия' },
  PNA: { make: 'Kia', manufacturer: 'Naza/Kia/Peugeot', country: 'Малайзия' },
  PNV: { make: 'Volvo', manufacturer: 'Volvo Cars', country: 'Малайзия' },
  PP1: { make: 'Mazda', manufacturer: 'Mazda', country: 'Малайзия' },
  PP3: { make: 'Hyundai', manufacturer: 'Hyundai', country: 'Малайзия' },
  PPP: { make: 'Suzuki', manufacturer: 'Suzuki', country: 'Малайзия' },
  PPV: { make: 'Volkswagen', manufacturer: 'Volkswagen', country: 'Малайзия' },
  PR8: { make: 'Ford', manufacturer: 'Ford', country: 'Малайзия' },
  PRH: { make: 'Chery', manufacturer: 'Chery', country: 'Малайзия' },
  PRN: { make: 'GAC', manufacturer: 'GAC Trumpchi made by Warisan Tan Chong Automotif Malaysia', country: 'Малайзия' },
  R4N: { make: 'Smart', manufacturer: 'Elyx Smart Technology Holdings Ltd.', country: 'Саудовская Аравия' },
  RHA: { make: 'Ford', manufacturer: 'Ford Lio Ho Motor Co Ltd new designation', country: 'Тайвань' },
  RKL: { make: 'Toyota', manufacturer: 'Kuozui Motors', country: 'Тайвань' },
  RKT: { make: 'Honda', manufacturer: 'Honda Taiwan', country: 'Тайвань' },
  RL0: { make: 'Ford', manufacturer: 'Ford Vietnam', country: 'Вьетнам' },
  RL4: { make: 'VinFast', manufacturer: 'VinFast, Хайфон', country: 'Вьетнам' },
  RLA: { make: 'Mitsubishi', manufacturer: 'Vina Star Motors Corp. – Mitsubishi', country: 'Вьетнам' },
  RLE: { make: 'Isuzu', manufacturer: 'Isuzu Vietnam Co.', country: 'Вьетнам' },
  RLF: { make: 'BMW', manufacturer: 'BMW BMW cars 2003-2014 Vietnam', country: 'Вьетнам' },
  RLH: { make: 'Honda', manufacturer: 'Honda Vietnam Co. Ltd.', country: 'Вьетнам' },
  RLL: { make: 'VinFast', manufacturer: 'VinFast, Хайфон', country: 'Вьетнам' },
  RLM: { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz Vietnam', country: 'Вьетнам' },
  SAD: { make: 'Jaguar', manufacturer: 'Jaguar Land Rover (Jaguar SUV)', country: 'Великобритания' },
  SAH: { make: 'Honda', manufacturer: 'Honda made by Austin Rover Group', country: 'Великобритания' },
  SAJ: { make: 'Jaguar', manufacturer: 'Jaguar Land Rover (Jaguar)', country: 'Великобритания' },
  SAL: { make: 'Land Rover', manufacturer: 'Jaguar Land Rover (Land Rover)', country: 'Великобритания' },
  SAR: { make: 'Rover', manufacturer: 'Rover Group', country: 'Великобритания' },
  SAX: { make: 'Rover', manufacturer: 'Austin Rover Group including Sterling Cars', country: 'Великобритания' },
  SAZ: { make: 'Rover', manufacturer: 'Freight Rover', country: 'Великобритания' },
  SB1: {
    make: 'Toyota',
    manufacturer: 'Toyota Motor Manufacturing UK, Бернастон (Avensis, Auris, Corolla)',
    country: 'Великобритания',
  },
  SBC: { make: 'Iveco', manufacturer: 'Iveco Ford Truck', country: 'Великобритания' },
  SBL: { make: 'DAF', manufacturer: 'Leyland Motors & Leyland DAF', country: 'Великобритания' },
  SBM: { make: 'McLaren', manufacturer: 'McLaren Group', country: 'Великобритания' },
  SBV: {
    make: 'Kenworth',
    manufacturer: 'Kenworth & Peterbilt trucks made by Leyland Trucks',
    country: 'Великобритания',
  },
  SCA: { make: 'Rolls-Royce', manufacturer: 'Rolls-Royce Motor Cars, Гудвуд', country: 'Великобритания' },
  SCB: { make: 'Bentley', manufacturer: 'Bentley Motors, Кру', country: 'Великобритания' },
  SCC: { make: 'Lotus', manufacturer: 'Lotus Cars, Хетел', country: 'Великобритания' },
  SCF: { make: 'Aston Martin', manufacturer: 'Aston Martin Lagonda', country: 'Великобритания' },
  SCV: { make: 'Volvo', manufacturer: 'Volvo Truck & Bus', country: 'Великобритания' },
  SD7: { make: 'Aston Martin', manufacturer: 'Aston Martin SUVs', country: 'Великобритания' },
  SDF: { make: 'Dodge', manufacturer: 'Dodge Trucks – UK 1981–1984', country: 'Великобритания' },
  SDG: { make: 'Renault', manufacturer: 'Renault Trucks Industries 1985–1992', country: 'Великобритания' },
  SDP: { make: 'MG', manufacturer: 'MG Motor NAC MG UK & MG Motor UK', country: 'Великобритания' },
  SED: { make: 'Isuzu', manufacturer: 'IBC Vehicles', country: 'Великобритания' },
  SFA: { make: 'Ford', manufacturer: 'Ford of Britain', country: 'Великобритания' },
  SFZ: { make: 'Tesla', manufacturer: 'Tesla Roadster made by Lotus', country: 'Великобритания' },
  SHH: { make: 'Honda', manufacturer: 'Honda of the UK Manufacturing, Суиндон (Civic)', country: 'Великобритания' },
  SHS: { make: 'Honda', manufacturer: 'Honda of the UK Manufacturing, Суиндон (CR-V)', country: 'Великобритания' },
  SJA: { make: 'Bentley', manufacturer: 'Bentley SUV', country: 'Великобритания' },
  SJK: { make: 'Nissan', manufacturer: 'Nissan Motor Manufacturing UK Infiniti', country: 'Великобритания' },
  SJN: {
    make: 'Nissan',
    manufacturer: 'Nissan Motor Manufacturing UK, Сандерленд (Qashqai, Juke)',
    country: 'Великобритания',
  },
  SKA: { make: 'Vauxhall', manufacturer: 'Vauxhall Motors', country: 'Великобритания' },
  SLA: { make: 'Rolls-Royce', manufacturer: 'Rolls-Royce Motor Cars SUV', country: 'Великобритания' },
  SLV: { make: 'Volvo', manufacturer: 'Volvo Bus', country: 'Великобритания' },
  SZA: { make: 'Scania', manufacturer: 'Scania Production Slupsk', country: 'Польша' },
  TMA: { make: 'Hyundai', manufacturer: 'Hyundai Motor Manufacturing Czech, Ношовице (i30, Tucson)', country: 'Чехия' },
  TMB: { make: 'Škoda', manufacturer: 'Škoda Auto, Млада-Болеслав', country: 'Чехия' },
  TMC: { make: 'Hyundai', manufacturer: 'Hyundai Motor Manufacturing Czech SUV', country: 'Чехия' },
  TMP: { make: 'Škoda', manufacturer: 'Škoda Ostrov', country: 'Чехия' },
  TMT: { make: 'Tatra', manufacturer: 'Tatra, Копршивнице', country: 'Чехия' },
  TNA: { make: 'Daewoo', manufacturer: 'Avia/Daewoo Avia', country: 'Чехия' },
  TRU: { make: 'Audi', manufacturer: 'Audi Hungaria, Дьёр', country: 'Венгрия' },
  TSM: { make: 'Suzuki', manufacturer: 'Magyar Suzuki, Эстергом (Vitara, SX4 S-Cross, Swift)', country: 'Венгрия' },
  TW1: { make: 'Toyota', manufacturer: 'Toyota Caetano Portugal', country: 'Португалия' },
  TW3: { make: 'Renault', manufacturer: 'Renault Portuguesa SARL', country: 'Португалия' },
  TW7: { make: 'MINI', manufacturer: 'Mini Moke made by British Leyland & Austin Rover', country: 'Португалия' },
  TX5: { make: 'MINI', manufacturer: 'Mini Moke made by Cagiva', country: 'Португалия' },
  TYA: { make: 'Mitsubishi', manufacturer: 'Mitsubishi Fuso Truck and Bus Corp.', country: 'Португалия' },
  TYB: { make: 'Mitsubishi', manufacturer: 'Mitsubishi Fuso Truck and Bus Corp.', country: 'Португалия' },
  U5Y: { make: 'Kia', manufacturer: 'Kia Slovakia, Жилина (Ceed, Sportage)', country: 'Словакия' },
  U6Y: { make: 'Kia', manufacturer: 'Kia Slovakia, Жилина', country: 'Словакия' },
  UU1: {
    make: 'Renault',
    manufacturer: 'Automobile Dacia, Питешти (Logan, Sandero, Duster — в РФ под маркой Renault)',
    country: 'Румыния',
    ambiguous: ['Dacia'],
  },
  UU6: { make: 'Daewoo', manufacturer: 'Daewoo Romania', country: 'Румыния' },
  VAG: { make: 'Mercedes-Benz', manufacturer: 'Steyr-Daimler-Puch Puch G & Steyr-Puch Pinzgauer', country: 'Австрия' },
  VAN: { make: 'Mercedes-Benz', manufacturer: 'Steyr-Daimler-Puch Steyr Trucks', country: 'Австрия' },
  VF1: { make: 'Renault', manufacturer: 'Renault', country: 'Франция' },
  VF2: { make: 'Renault', manufacturer: 'Renault Trucks', country: 'Франция' },
  VF3: { make: 'Peugeot', manufacturer: 'Peugeot', country: 'Франция' },
  VF5: { make: 'Iveco', manufacturer: 'Iveco Unic', country: 'Франция' },
  VF6: { make: 'Renault Trucks', manufacturer: 'Renault Trucks', country: 'Франция' },
  VF7: { make: 'Citroën', manufacturer: 'Citroën', country: 'Франция' },
  VG6: {
    make: 'Renault',
    manufacturer: 'Renault Trucks & Mack Trucks medium duty trucks made by Renault Trucks',
    country: 'Франция',
  },
  VGA: { make: 'Peugeot', manufacturer: 'Peugeot Motocycles', country: 'Франция' },
  VLU: { make: 'Scania', manufacturer: 'Scania Production Angers', country: 'Франция' },
  VMK: { make: 'Renault', manufacturer: 'Renault Sport Spider', country: 'Франция' },
  VN1: { make: 'Renault', manufacturer: 'Renault SOVAB', country: 'Франция' },
  VNE: { make: 'Iveco', manufacturer: 'Iveco Bus', country: 'Франция' },
  VNK: { make: 'Toyota', manufacturer: 'Toyota Motor Manufacturing France, Валансьен (Yaris)', country: 'Франция' },
  VNV: { make: 'Nissan', manufacturer: 'Nissan', country: 'Франция' },
  VR1: { make: 'DS', manufacturer: 'DS Automobiles', country: 'Франция' },
  VR3: { make: 'Peugeot', manufacturer: 'Peugeot', country: 'Франция' },
  VR7: { make: 'Citroën', manufacturer: 'Citroën', country: 'Франция' },
  VS5: { make: 'Renault', manufacturer: 'Renault España, Вальядолид / Паленсия', country: 'Испания' },
  VS6: { make: 'Ford', manufacturer: 'Ford España, Валенсия', country: 'Испания' },
  VS7: { make: 'Citroën', manufacturer: 'Citroën, Виго', country: 'Испания' },
  VS8: { make: 'Peugeot', manufacturer: 'Peugeot, Мадрид', country: 'Испания' },
  VSC: { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz Espana SA', country: 'Испания' },
  VSE: { make: 'Suzuki', manufacturer: 'Santana Motor (сборка Suzuki)', country: 'Испания' },
  VSK: { make: 'Nissan', manufacturer: 'Nissan Motor Ibérica, Барселона', country: 'Испания' },
  VSS: { make: 'SEAT', manufacturer: 'SEAT, Марторель', country: 'Испания' },
  VSX: { make: 'Opel', manufacturer: 'Opel España, Сарагоса', country: 'Испания' },
  VWA: {
    make: 'Nissan',
    manufacturer: 'Nissan Vehiculos Industriales SA, Nissan Commercial Vehicles',
    country: 'Испания',
  },
  VWV: { make: 'Volkswagen', manufacturer: 'Volkswagen Navarra, Памплона (Polo)', country: 'Испания' },
  VX1: { make: 'Zastava', manufacturer: 'Zastava, Крагуевац (Yugo)', country: 'Сербия' },
  VXE: { make: 'Opel', manufacturer: 'Opel Automobile GmbH/Vauxhall van', country: 'Сербия' },
  VXK: { make: 'Opel', manufacturer: 'Opel Automobile GmbH/Vauxhall car/SUV', country: 'Сербия' },
  VYC: { make: 'Lancia', manufacturer: 'Lancia', country: 'Сербия' },
  W04: { make: 'Buick', manufacturer: 'Buick Regal & Buick Cascada', country: 'Германия' },
  W06: { make: 'Cadillac', manufacturer: 'Cadillac Catera', country: 'Германия' },
  W08: { make: 'Saturn', manufacturer: 'Saturn Astra', country: 'Германия' },
  W0L: {
    make: 'Opel',
    manufacturer: 'Opel Automobile, Рюссельсхайм (также Vauxhall)',
    country: 'Германия',
    ambiguous: ['Vauxhall'],
  },
  W0S: { make: 'Opel', manufacturer: 'Opel Special Vehicles', country: 'Германия' },
  W0V: { make: 'Opel', manufacturer: 'Opel Automobile (также Vauxhall)', country: 'Германия', ambiguous: ['Vauxhall'] },
  W1A: { make: 'Smart', manufacturer: 'Smart', country: 'Германия' },
  W1H: { make: 'Freightliner', manufacturer: 'Freightliner Econic', country: 'Германия' },
  W1K: { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz (легковые)', country: 'Германия' },
  W1N: { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz (SUV)', country: 'Германия' },
  W1T: { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz truck', country: 'Германия' },
  W1V: { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz (вэны)', country: 'Германия' },
  W1W: { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz MPV', country: 'Германия' },
  W1X: { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz incomplete vehicle', country: 'Германия' },
  W1Y: { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz truck', country: 'Германия' },
  W1Z: { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz "bus"', country: 'Германия' },
  W2W: { make: 'Freightliner', manufacturer: 'Freightliner Sprinter MPV', country: 'Германия' },
  W2X: { make: 'Freightliner', manufacturer: 'Freightliner Sprinter incomplete vehicle', country: 'Германия' },
  W2Y: { make: 'Freightliner', manufacturer: 'Freightliner Sprinter truck', country: 'Германия' },
  W2Z: { make: 'Freightliner', manufacturer: 'Freightliner Sprinter "bus"', country: 'Германия' },
  WA1: { make: 'Audi', manufacturer: 'Audi (SUV)', country: 'Германия' },
  WAC: { make: 'Audi', manufacturer: 'Audi/Porsche RS 2 Avant', country: 'Германия' },
  WAG: { make: 'Neoplan', manufacturer: 'Neoplan (MAN Truck & Bus)', country: 'Германия' },
  WAU: { make: 'Audi', manufacturer: 'Audi (легковые)', country: 'Германия' },
  WB5: { make: 'BMW', manufacturer: 'BMW i SUV', country: 'Германия' },
  WB6: { make: 'BMW', manufacturer: 'BMW M SUV', country: 'Германия' },
  WBA: { make: 'BMW', manufacturer: 'BMW (легковые)', country: 'Германия' },
  WBS: { make: 'BMW', manufacturer: 'BMW M', country: 'Германия' },
  WBX: { make: 'BMW', manufacturer: 'BMW (SUV)', country: 'Германия' },
  WBY: { make: 'BMW', manufacturer: 'BMW i', country: 'Германия' },
  WCD: { make: 'Freightliner', manufacturer: 'Freightliner Sprinter "bus" 2008–2019', country: 'Германия' },
  WD0: { make: 'Dodge', manufacturer: 'Dodge Sprinter truck 2005–2009', country: 'Германия' },
  WD1: {
    make: 'Freightliner',
    manufacturer: 'Freightliner Sprinter 2002 & Sprinter 2003–2005 incomplete vehicle',
    country: 'Германия',
  },
  WD2: {
    make: 'Freightliner',
    manufacturer: 'Freightliner Sprinter 2002 & Sprinter 2003–2005 truck',
    country: 'Германия',
  },
  WD3: { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz truck', country: 'Германия' },
  WD4: { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz MPV', country: 'Германия' },
  WD5: {
    make: 'Freightliner',
    manufacturer: 'Freightliner Sprinter 2002 & Sprinter 2003–2005 MPV',
    country: 'Германия',
  },
  WD6: { make: 'Freightliner', manufacturer: 'Freightliner Unimog truck', country: 'Германия' },
  WD7: { make: 'Freightliner', manufacturer: 'Freightliner Unimog incomplete vehicle', country: 'Германия' },
  WD8: { make: 'Dodge', manufacturer: 'Dodge Sprinter MPV 2005–2009', country: 'Германия' },
  WDA: { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz incomplete vehicle', country: 'Германия' },
  WDB: { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz', country: 'Германия' },
  WDC: { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz (SUV)', country: 'Германия' },
  WDD: { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz (легковые)', country: 'Германия' },
  WDF: { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz (вэны)', country: 'Германия' },
  WDP: {
    make: 'Freightliner',
    manufacturer: 'Freightliner Sprinter incomplete vehicle 2005–2019',
    country: 'Германия',
  },
  WDR: { make: 'Freightliner', manufacturer: 'Freightliner Sprinter MPV 2005–2019', country: 'Германия' },
  WDW: { make: 'Dodge', manufacturer: 'Dodge Sprinter "bus" 2008–2009', country: 'Германия' },
  WDX: { make: 'Dodge', manufacturer: 'Dodge Sprinter incomplete vehicle 2005–2009', country: 'Германия' },
  WDY: { make: 'Freightliner', manufacturer: 'Freightliner Sprinter truck 2005–2019', country: 'Германия' },
  WDZ: { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz "bus"', country: 'Германия' },
  WEB: { make: 'Mercedes-Benz', manufacturer: 'EvoBus Mercedes-Benz buses', country: 'Германия' },
  WF0: { make: 'Ford', manufacturer: 'Ford-Werke, Кёльн', country: 'Германия' },
  WJM: { make: 'Iveco', manufacturer: 'Iveco/Iveco Magirus', country: 'Германия' },
  WKK: { make: 'Mercedes-Benz', manufacturer: 'Setra & Karl Kässbohrer Fahrzeugwerke', country: 'Германия' },
  WMA: { make: 'MAN', manufacturer: 'MAN Truck & Bus', country: 'Германия' },
  WME: { make: 'Smart', manufacturer: 'Smart', country: 'Германия' },
  WMW: { make: 'MINI', manufacturer: 'BMW (MINI), Оксфорд', country: 'Великобритания' },
  WMX: { make: 'Mercedes-AMG', manufacturer: 'Mercedes-AMG, Аффальтербах', country: 'Германия' },
  WMZ: { make: 'MINI', manufacturer: 'Mini SUV', country: 'Германия' },
  WP0: { make: 'Porsche', manufacturer: 'Porsche (легковые)', country: 'Германия' },
  WP1: { make: 'Porsche', manufacturer: 'Porsche (SUV)', country: 'Германия' },
  WU1: { make: 'Audi', manufacturer: 'Audi Sport GmbH SUV', country: 'Германия' },
  WUA: { make: 'Audi', manufacturer: 'Audi Sport (RS)', country: 'Германия' },
  WV1: { make: 'Volkswagen', manufacturer: 'Volkswagen (коммерческие)', country: 'Германия' },
  WV2: { make: 'Volkswagen', manufacturer: 'Volkswagen (Transporter, Multivan)', country: 'Германия' },
  WVG: { make: 'Volkswagen', manufacturer: 'Volkswagen (SUV)', country: 'Германия' },
  WVM: { make: 'Volkswagen', manufacturer: 'Arbeitsgemeinschaft VW-MAN', country: 'Германия' },
  WVW: { make: 'Volkswagen', manufacturer: 'Volkswagen (легковые)', country: 'Германия' },
  WZ1: { make: 'Toyota', manufacturer: 'Toyota Supra Fifth generation', country: 'Германия' },
  // ── Америка ──
  '137': { make: 'Hummer', manufacturer: 'AM General Hummer & Hummer H1', country: 'США' },
  '19U': { make: 'Acura', manufacturer: 'Acura car made by Honda of America Mfg. in Ohio', country: 'США' },
  '19V': { make: 'Acura', manufacturer: 'Acura car made by Honda Manufacturing of Indiana', country: 'США' },
  '19X': { make: 'Honda', manufacturer: 'Honda car made by Honda Manufacturing of Indiana', country: 'США' },
  '1AM': {
    make: 'Renault',
    manufacturer: 'American Motors Corporation car & Renault Alliance 1983 only',
    country: 'США',
  },
  '1B3': { make: 'Dodge', manufacturer: 'Dodge car 1981–2011', country: 'США' },
  '1B4': { make: 'Dodge', manufacturer: 'Dodge MPV/SUV 1981–2002', country: 'США' },
  '1B6': { make: 'Dodge', manufacturer: 'Dodge incomplete vehicle 1981–2002', country: 'США' },
  '1B7': { make: 'Dodge', manufacturer: 'Dodge truck 1981–2002', country: 'США' },
  '1C3': { make: 'Chrysler', manufacturer: 'Chrysler brand car 1981–2011', country: 'США' },
  '1C4': {
    make: 'Jeep',
    manufacturer: 'FCA US (Jeep; также Chrysler, Dodge)',
    country: 'США',
    ambiguous: ['Chrysler', 'Dodge'],
  },
  '1C6': { make: 'Ram', manufacturer: 'FCA US (Ram)', country: 'США' },
  '1C8': { make: 'Chrysler', manufacturer: 'Chrysler brand MPV 2001–2005', country: 'США' },
  '1D3': { make: 'Dodge', manufacturer: 'Dodge truck 2002–2009', country: 'США' },
  '1D4': { make: 'Dodge', manufacturer: 'Dodge MPV/SUV 2003–2011 only', country: 'США' },
  '1D7': { make: 'Dodge', manufacturer: 'Dodge truck 2002–2011', country: 'США' },
  '1D8': { make: 'Dodge', manufacturer: 'Dodge MPV/SUV 2003–2009 only', country: 'США' },
  '1F1': { make: 'Ford', manufacturer: 'Ford SUV – limousine', country: 'США' },
  '1F6': { make: 'Ford', manufacturer: 'Ford stripped chassis made by Detroit Chassis LLC', country: 'США' },
  '1FA': { make: 'Ford', manufacturer: 'Ford Motor Company (легковые)', country: 'США' },
  '1FB': { make: 'Ford', manufacturer: 'Ford "bus"', country: 'США' },
  '1FC': { make: 'Ford', manufacturer: 'Ford stripped chassis made by Ford', country: 'США' },
  '1FD': { make: 'Ford', manufacturer: 'Ford incomplete vehicle', country: 'США' },
  '1FM': { make: 'Ford', manufacturer: 'Ford Motor Company (SUV)', country: 'США' },
  '1FT': { make: 'Ford', manufacturer: 'Ford Motor Company (пикапы)', country: 'США' },
  '1G0': { make: 'GMC', manufacturer: 'GMC "bus" 1981–1986', country: 'США' },
  '1G1': { make: 'Chevrolet', manufacturer: 'General Motors (Chevrolet, легковые)', country: 'США' },
  '1G2': { make: 'Pontiac', manufacturer: 'Pontiac car', country: 'США' },
  '1G3': { make: 'Oldsmobile', manufacturer: 'Oldsmobile car', country: 'США' },
  '1G4': { make: 'Buick', manufacturer: 'General Motors (Buick)', country: 'США' },
  '1G5': { make: 'GMC', manufacturer: 'GMC MPV/SUV 1981–1986', country: 'США' },
  '1G6': { make: 'Cadillac', manufacturer: 'General Motors (Cadillac)', country: 'США' },
  '1G7': { make: 'Pontiac', manufacturer: 'Pontiac car only sold by GM Canada', country: 'США' },
  '1G8': { make: 'Chevrolet', manufacturer: 'Chevrolet MPV/SUV 1981–1986', country: 'США' },
  '1GA': { make: 'Chevrolet', manufacturer: 'Chevrolet "bus"', country: 'США' },
  '1GB': { make: 'Chevrolet', manufacturer: 'Chevrolet incomplete vehicles', country: 'США' },
  '1GC': { make: 'Chevrolet', manufacturer: 'General Motors (Chevrolet, пикапы)', country: 'США' },
  '1GD': { make: 'GMC', manufacturer: 'GMC incomplete vehicles', country: 'США' },
  '1GE': { make: 'Cadillac', manufacturer: 'Cadillac incomplete vehicle', country: 'США' },
  '1GG': { make: 'Isuzu', manufacturer: 'Isuzu pickup trucks made by GM', country: 'США' },
  '1GH': { make: 'Oldsmobile', manufacturer: 'Oldsmobile MPV/SUV 1990–2004', country: 'США' },
  '1GJ': { make: 'GMC', manufacturer: 'GMC "bus" 1987–', country: 'США' },
  '1GK': { make: 'GMC', manufacturer: 'General Motors (GMC, SUV)', country: 'США' },
  '1GM': { make: 'Pontiac', manufacturer: 'Pontiac MPV', country: 'США' },
  '1GN': { make: 'Chevrolet', manufacturer: 'General Motors (Chevrolet, SUV)', country: 'США' },
  '1GT': { make: 'GMC', manufacturer: 'General Motors (GMC, пикапы)', country: 'США' },
  '1GY': { make: 'Cadillac', manufacturer: 'General Motors (Cadillac, SUV)', country: 'США' },
  '1HA': {
    make: 'Chevrolet',
    manufacturer: 'Chevrolet incomplete vehicles made by Navistar International',
    country: 'США',
  },
  '1HG': { make: 'Honda', manufacturer: 'Honda of America (легковые)', country: 'США' },
  '1HS': { make: 'International', manufacturer: 'International Trucks & Caterpillar Trucks truck', country: 'США' },
  '1HT': {
    make: 'International',
    manufacturer: 'International Trucks & Caterpillar Trucks & Chevrolet Silverado 4500HD, 5500HD, ',
    country: 'США',
  },
  '1J4': { make: 'Jeep', manufacturer: 'Chrysler Group (Jeep)', country: 'США' },
  '1J7': { make: 'Jeep', manufacturer: 'Jeep truck 1989–1992', country: 'США' },
  '1J8': { make: 'Jeep', manufacturer: 'Jeep SUV 2002–2011', country: 'США' },
  '1JC': { make: 'Jeep', manufacturer: 'Jeep SUV 1981–1988', country: 'США' },
  '1JT': { make: 'Jeep', manufacturer: 'Jeep truck 1981–1988', country: 'США' },
  '1L1': { make: 'Lincoln', manufacturer: 'Lincoln car – limousine', country: 'США' },
  '1LJ': { make: 'Lincoln', manufacturer: 'Lincoln incomplete vehicle', country: 'США' },
  '1LN': { make: 'Lincoln', manufacturer: 'Lincoln car', country: 'США' },
  '1MB': { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz Truck Co.', country: 'США' },
  '1ME': { make: 'Mercury', manufacturer: 'Mercury car', country: 'США' },
  '1N4': { make: 'Nissan', manufacturer: 'Nissan North America, Смирна (легковые)', country: 'США' },
  '1N6': { make: 'Nissan', manufacturer: 'Nissan truck', country: 'США' },
  '1NK': { make: 'Kenworth', manufacturer: 'Kenworth incomplete vehicle', country: 'США' },
  '1NP': { make: 'Peterbilt', manufacturer: 'Peterbilt incomplete vehicle', country: 'США' },
  '1NX': { make: 'Toyota', manufacturer: 'NUMMI, Фримонт (Corolla)', country: 'США' },
  '1P3': { make: 'Plymouth', manufacturer: 'Plymouth car', country: 'США' },
  '1P4': { make: 'Plymouth', manufacturer: 'Plymouth MPV/SUV', country: 'США' },
  '1UT': { make: 'Jeep', manufacturer: 'Jeep DJ made by AM General', country: 'США' },
  '1V1': { make: 'Volkswagen', manufacturer: 'Volkswagen truck', country: 'США' },
  '1V2': { make: 'Volkswagen', manufacturer: 'Volkswagen SUV', country: 'США' },
  '1VW': { make: 'Volkswagen', manufacturer: 'Volkswagen Chattanooga', country: 'США' },
  '1XK': { make: 'Kenworth', manufacturer: 'Kenworth truck', country: 'США' },
  '1XM': { make: 'Renault', manufacturer: 'Renault Alliance/GTA/Encore 1984–1987', country: 'США' },
  '1XP': { make: 'Peterbilt', manufacturer: 'Peterbilt truck', country: 'США' },
  '1Y1': { make: 'Chevrolet', manufacturer: 'Chevrolet/Geo car made by NUMMI', country: 'США' },
  '1YV': { make: 'Mazda', manufacturer: 'Mazda', country: 'США' },
  '1ZV': { make: 'Ford', manufacturer: 'Ford made by AutoAlliance International', country: 'США' },
  '1ZW': { make: 'Mercury', manufacturer: 'Mercury made by AutoAlliance International', country: 'США' },
  '2B3': { make: 'Dodge', manufacturer: 'Dodge car 1981–2011', country: 'Канада' },
  '2B4': { make: 'Dodge', manufacturer: 'Dodge MPV 1981–2002', country: 'Канада' },
  '2B5': { make: 'Dodge', manufacturer: 'Dodge "bus" 1981–2002', country: 'Канада' },
  '2B6': { make: 'Dodge', manufacturer: 'Dodge incomplete vehicle 1981–2002', country: 'Канада' },
  '2B7': { make: 'Dodge', manufacturer: 'Dodge truck 1981–2002', country: 'Канада' },
  '2BC': { make: 'Jeep', manufacturer: 'Jeep Wrangler 1987–1988', country: 'Канада' },
  '2C1': { make: 'Chevrolet', manufacturer: 'Geo/Chevrolet car made by CAMI Automotive', country: 'Канада' },
  '2C3': { make: 'Chrysler', manufacturer: 'Chrysler brand car 1981–2011', country: 'Канада' },
  '2C4': { make: 'Chrysler', manufacturer: 'Chrysler brand MPV/SUV 2000–2005', country: 'Канада' },
  '2C7': {
    make: 'Pontiac',
    manufacturer: 'Pontiac car made by CAMI Automotive only sold by GM Canada',
    country: 'Канада',
  },
  '2C8': { make: 'Chrysler', manufacturer: 'Chrysler brand MPV/SUV 2001–2005', country: 'Канада' },
  '2CG': {
    make: 'Pontiac',
    manufacturer: 'Asüna/Pontiac SUV made by CAMI Automotive only sold by GM Canada',
    country: 'Канада',
  },
  '2CK': {
    make: 'GMC',
    manufacturer: 'GMC Tracker SUV made by CAMI Automotive only sold by GM Canada 1990–1991 only',
    country: 'Канада',
  },
  '2CN': {
    make: 'Chevrolet',
    manufacturer: 'Geo/Chevrolet SUV made by CAMI Automotive 1990–2011 only',
    country: 'Канада',
  },
  '2CT': { make: 'GMC', manufacturer: 'GMC Terrain SUV made by CAMI Automotive 2010–2011 only', country: 'Канада' },
  '2D4': { make: 'Dodge', manufacturer: 'Dodge MPV 2003–2011 only', country: 'Канада' },
  '2D6': { make: 'Dodge', manufacturer: 'Dodge incomplete vehicle 2003', country: 'Канада' },
  '2D7': { make: 'Dodge', manufacturer: 'Dodge truck 2003', country: 'Канада' },
  '2D8': { make: 'Dodge', manufacturer: 'Dodge MPV 2003–2011 only', country: 'Канада' },
  '2E3': { make: 'Chrysler', manufacturer: 'Eagle car 1989–1997', country: 'Канада' },
  '2E4': { make: 'Lancia', manufacturer: 'Lancia MPV', country: 'Канада' },
  '2FA': { make: 'Ford', manufacturer: 'Ford car', country: 'Канада' },
  '2FM': { make: 'Ford', manufacturer: 'Ford MPV/SUV', country: 'Канада' },
  '2FT': { make: 'Ford', manufacturer: 'Ford truck', country: 'Канада' },
  '2G0': { make: 'GMC', manufacturer: 'GMC "bus" 1981–1986', country: 'Канада' },
  '2G1': { make: 'Chevrolet', manufacturer: 'Chevrolet', country: 'Канада' },
  '2G2': { make: 'Pontiac', manufacturer: 'Pontiac', country: 'Канада' },
  '2G3': { make: 'Oldsmobile', manufacturer: 'Oldsmobile car', country: 'Канада' },
  '2G4': { make: 'Buick', manufacturer: 'Buick', country: 'Канада' },
  '2G5': { make: 'GMC', manufacturer: 'GMC MPV 1981–1986; BrightDrop Zevo delivery van', country: 'Канада' },
  '2G6': { make: 'Cadillac', manufacturer: 'Cadillac', country: 'Канада' },
  '2G7': { make: 'Pontiac', manufacturer: 'Pontiac car only sold by GM Canada', country: 'Канада' },
  '2G8': { make: 'Chevrolet', manufacturer: 'Chevrolet MPV 1981–1986', country: 'Канада' },
  '2GA': { make: 'Chevrolet', manufacturer: 'Chevrolet "bus"', country: 'Канада' },
  '2GB': { make: 'Chevrolet', manufacturer: 'Chevrolet incomplete vehicles', country: 'Канада' },
  '2GC': { make: 'Chevrolet', manufacturer: 'Chevrolet truck', country: 'Канада' },
  '2GD': { make: 'GMC', manufacturer: 'GMC incomplete vehicles', country: 'Канада' },
  '2GE': { make: 'Cadillac', manufacturer: 'Cadillac incomplete vehicle', country: 'Канада' },
  '2GH': { make: 'GMC', manufacturer: 'GMC GM New Look bus & GM Classic series bus', country: 'Канада' },
  '2GJ': { make: 'GMC', manufacturer: 'GMC "bus" 1987–', country: 'Канада' },
  '2GK': { make: 'GMC', manufacturer: 'GMC MPV/SUV 1987–', country: 'Канада' },
  '2GN': { make: 'Chevrolet', manufacturer: 'Chevrolet MPV/SUV 1987-', country: 'Канада' },
  '2GT': { make: 'GMC', manufacturer: 'GMC truck', country: 'Канада' },
  '2HG': { make: 'Honda', manufacturer: 'Honda of Canada (Civic)', country: 'Канада' },
  '2HH': { make: 'Acura', manufacturer: 'Acura car made by Honda of Canada Manufacturing', country: 'Канада' },
  '2HJ': { make: 'Honda', manufacturer: 'Honda truck made by Honda of Canada Manufacturing', country: 'Канада' },
  '2HK': { make: 'Honda', manufacturer: 'Honda of Canada (CR-V)', country: 'Канада' },
  '2HM': { make: 'Hyundai', manufacturer: 'Hyundai Auto Canada, Бромон', country: 'Канада' },
  '2HN': { make: 'Acura', manufacturer: 'Acura SUV made by Honda of Canada Manufacturing', country: 'Канада' },
  '2HS': { make: 'International', manufacturer: 'International Trucks truck', country: 'Канада' },
  '2HT': { make: 'International', manufacturer: 'International Trucks incomplete vehicle', country: 'Канада' },
  '2J4': { make: 'Jeep', manufacturer: 'Jeep Wrangler 1989–1992', country: 'Канада' },
  '2L1': { make: 'Lincoln', manufacturer: 'Lincoln incomplete vehicle – limo', country: 'Канада' },
  '2LJ': { make: 'Lincoln', manufacturer: 'Lincoln incomplete vehicle – hearse', country: 'Канада' },
  '2LM': { make: 'Lincoln', manufacturer: 'Lincoln SUV', country: 'Канада' },
  '2LN': { make: 'Lincoln', manufacturer: 'Lincoln car', country: 'Канада' },
  '2ME': { make: 'Mercury', manufacturer: 'Mercury car', country: 'Канада' },
  '2MR': { make: 'Mercury', manufacturer: 'Mercury MPV', country: 'Канада' },
  '2NK': { make: 'Kenworth', manufacturer: 'Kenworth incomplete vehicle', country: 'Канада' },
  '2NP': { make: 'Peterbilt', manufacturer: 'Peterbilt incomplete vehicle', country: 'Канада' },
  '2P3': { make: 'Plymouth', manufacturer: 'Plymouth car', country: 'Канада' },
  '2P4': { make: 'Plymouth', manufacturer: 'Plymouth MPV 1981–2000', country: 'Канада' },
  '2P5': { make: 'Plymouth', manufacturer: 'Plymouth "bus" 1981–1983', country: 'Канада' },
  '2S2': { make: 'Suzuki', manufacturer: 'Suzuki car made by CAMI Automotive', country: 'Канада' },
  '2S3': { make: 'Suzuki', manufacturer: 'Suzuki SUV made by CAMI Automotive', country: 'Канада' },
  '2T1': { make: 'Toyota', manufacturer: 'Toyota Motor Manufacturing Canada (Corolla)', country: 'Канада' },
  '2T2': { make: 'Lexus', manufacturer: 'Lexus SUV', country: 'Канада' },
  '2T3': { make: 'Toyota', manufacturer: 'Toyota SUV', country: 'Канада' },
  '2WK': { make: 'Western Star', manufacturer: 'Western Star Trucks truck', country: 'Канада' },
  '2XK': { make: 'Kenworth', manufacturer: 'Kenworth truck', country: 'Канада' },
  '2XP': { make: 'Peterbilt', manufacturer: 'Peterbilt truck', country: 'Канада' },
  '3AV': { make: 'BMW', manufacturer: 'BMW Mexico 1999-2009', country: 'Мексика' },
  '3B3': { make: 'Dodge', manufacturer: 'Dodge car 1981–2011', country: 'Мексика' },
  '3B4': { make: 'Dodge', manufacturer: 'Dodge SUV 1986–1993', country: 'Мексика' },
  '3B6': { make: 'Dodge', manufacturer: 'Dodge incomplete vehicle 1981–2002', country: 'Мексика' },
  '3B7': { make: 'Dodge', manufacturer: 'Dodge truck 1981–2002', country: 'Мексика' },
  '3BJ': { make: 'Western Star', manufacturer: 'Western Star 3700 truck made by DINA S.A.', country: 'Мексика' },
  '3BK': { make: 'Kenworth', manufacturer: 'Kenworth incomplete vehicle', country: 'Мексика' },
  '3BP': { make: 'Peterbilt', manufacturer: 'Peterbilt incomplete vehicle', country: 'Мексика' },
  '3C3': { make: 'Chrysler', manufacturer: 'Chrysler brand car 1981–2011', country: 'Мексика' },
  '3C4': { make: 'Chrysler', manufacturer: 'Chrysler brand MPV 2001–2005', country: 'Мексика' },
  '3C6': { make: 'Chrysler', manufacturer: 'Chrysler Group truck 2012–', country: 'Мексика' },
  '3C7': { make: 'Chrysler', manufacturer: 'Chrysler Group incomplete vehicle 2012–', country: 'Мексика' },
  '3C8': { make: 'Chrysler', manufacturer: 'Chrysler brand MPV 2001–2005', country: 'Мексика' },
  '3CE': { make: 'Volvo', manufacturer: 'Volvo Buses de Mexico', country: 'Мексика' },
  '3CZ': { make: 'Honda', manufacturer: 'Honda SUV', country: 'Мексика' },
  '3D2': { make: 'Dodge', manufacturer: 'Dodge incomplete vehicle 2007–2009', country: 'Мексика' },
  '3D3': { make: 'Dodge', manufacturer: 'Dodge truck 2006–2009', country: 'Мексика' },
  '3D4': { make: 'Dodge', manufacturer: 'Dodge SUV 2009–2011', country: 'Мексика' },
  '3D6': { make: 'Dodge', manufacturer: 'Dodge incomplete vehicle 2003–2011', country: 'Мексика' },
  '3D7': { make: 'Dodge', manufacturer: 'Dodge truck 2002–2011', country: 'Мексика' },
  '3E4': { make: 'Fiat', manufacturer: 'Fiat SUV', country: 'Мексика' },
  '3FA': { make: 'Ford', manufacturer: 'Ford de México, Эрмосильо (Fusion)', country: 'Мексика' },
  '3FC': { make: 'Ford', manufacturer: 'Ford stripped chassis made by Ford & IMMSA', country: 'Мексика' },
  '3FM': { make: 'Ford', manufacturer: 'Ford MPV/SUV', country: 'Мексика' },
  '3FT': { make: 'Ford', manufacturer: 'Ford truck', country: 'Мексика' },
  '3G0': { make: 'Saab', manufacturer: 'Saab 9-4X 2011', country: 'Мексика' },
  '3G1': { make: 'Chevrolet', manufacturer: 'Chevrolet car', country: 'Мексика' },
  '3G2': { make: 'Pontiac', manufacturer: 'Pontiac car', country: 'Мексика' },
  '3G4': { make: 'Buick', manufacturer: 'Buick car', country: 'Мексика' },
  '3G5': { make: 'Buick', manufacturer: 'Buick SUV', country: 'Мексика' },
  '3G7': { make: 'Pontiac', manufacturer: 'Pontiac SUV', country: 'Мексика' },
  '3GC': { make: 'Chevrolet', manufacturer: 'Chevrolet truck', country: 'Мексика' },
  '3GK': { make: 'GMC', manufacturer: 'GMC SUV', country: 'Мексика' },
  '3GM': { make: 'Holden', manufacturer: 'Holden Suburban', country: 'Мексика' },
  '3GN': { make: 'Chevrolet', manufacturer: 'Chevrolet SUV', country: 'Мексика' },
  '3GS': { make: 'Saturn', manufacturer: 'Saturn SUV', country: 'Мексика' },
  '3GT': { make: 'GMC', manufacturer: 'GMC truck', country: 'Мексика' },
  '3GY': { make: 'Cadillac', manufacturer: 'Cadillac SUV', country: 'Мексика' },
  '3HA': { make: 'International', manufacturer: 'International Trucks incomplete vehicle', country: 'Мексика' },
  '3HC': { make: 'International', manufacturer: 'International Trucks truck', country: 'Мексика' },
  '3HG': { make: 'Honda', manufacturer: 'Honda de México, Селая', country: 'Мексика' },
  '3HS': { make: 'International', manufacturer: 'International Trucks & Caterpillar Trucks truck', country: 'Мексика' },
  '3HT': {
    make: 'International',
    manufacturer: 'International Trucks & Caterpillar Trucks incomplete vehicle',
    country: 'Мексика',
  },
  '3KP': { make: 'Kia', manufacturer: 'Kia México, Пескерия (Rio, Forte)', country: 'Мексика' },
  '3LN': { make: 'Lincoln', manufacturer: 'Lincoln car', country: 'Мексика' },
  '3MD': { make: 'Mazda', manufacturer: 'Mazda car', country: 'Мексика' },
  '3ME': { make: 'Mercury', manufacturer: 'Mercury car', country: 'Мексика' },
  '3MV': { make: 'Mazda', manufacturer: 'Mazda SUV', country: 'Мексика' },
  '3MW': { make: 'BMW', manufacturer: 'BMW San Luis Potosí', country: 'Мексика' },
  '3MY': { make: 'Toyota', manufacturer: 'Toyota car made by Mazda de Mexico Vehicle Operation', country: 'Мексика' },
  '3MZ': { make: 'Mazda', manufacturer: 'Mazda de México, Саламанка', country: 'Мексика' },
  '3N1': { make: 'Nissan', manufacturer: 'Nissan Mexicana (легковые)', country: 'Мексика' },
  '3N6': { make: 'Nissan', manufacturer: 'Nissan truck & Chevrolet City Express', country: 'Мексика' },
  '3N8': { make: 'Nissan', manufacturer: 'Nissan MPV', country: 'Мексика' },
  '3P3': { make: 'Plymouth', manufacturer: 'Plymouth car', country: 'Мексика' },
  '3PC': { make: 'Infiniti', manufacturer: 'Infiniti SUV made by COMPAS', country: 'Мексика' },
  '3TM': { make: 'Toyota', manufacturer: 'Toyota truck made by TMMBC', country: 'Мексика' },
  '3TY': { make: 'Toyota', manufacturer: 'Toyota truck made by TMMGT', country: 'Мексика' },
  '3VV': { make: 'Volkswagen', manufacturer: 'Volkswagen SUV', country: 'Мексика' },
  '3VW': {
    make: 'Volkswagen',
    manufacturer: 'Volkswagen de México, Пуэбла (Jetta, Beetle, Tiguan)',
    country: 'Мексика',
  },
  '3WK': { make: 'Kenworth', manufacturer: 'Kenworth truck', country: 'Мексика' },
  '3WP': { make: 'Peterbilt', manufacturer: 'Peterbilt truck', country: 'Мексика' },
  '4A3': { make: 'Mitsubishi', manufacturer: 'Mitsubishi Motors car', country: 'США' },
  '4A4': { make: 'Mitsubishi', manufacturer: 'Mitsubishi Motors SUV', country: 'США' },
  '4B3': { make: 'Dodge', manufacturer: 'Dodge car made by Diamond-Star Motors factory', country: 'США' },
  '4C3': { make: 'Chrysler', manufacturer: 'Chrysler car made by Diamond-Star Motors factory', country: 'США' },
  '4F2': { make: 'Mazda', manufacturer: 'Mazda SUV made by Ford', country: 'США' },
  '4F4': { make: 'Mazda', manufacturer: 'Mazda truck made by Ford', country: 'США' },
  '4G1': {
    make: 'Chevrolet',
    manufacturer: 'Chevrolet Cavalier convertible made by Genasys L.C. – a GM/ASC joint venture',
    country: 'США',
  },
  '4G2': {
    make: 'Pontiac',
    manufacturer: 'Pontiac Sunfire convertible made by Genasys L.C. – a GM/ASC joint venture',
    country: 'США',
  },
  '4G3': { make: 'Toyota', manufacturer: 'Toyota Cavalier made by GM', country: 'США' },
  '4GD': { make: 'Opel', manufacturer: 'Opel Sintra', country: 'США' },
  '4GL': { make: 'Buick', manufacturer: 'Buick incomplete vehicle', country: 'США' },
  '4GT': { make: 'Isuzu', manufacturer: 'Isuzu incomplete vehicle built by GM', country: 'США' },
  '4JG': {
    make: 'Mercedes-Benz',
    manufacturer: 'Mercedes-Benz U.S. International, Таскалуса (GLE, GLS)',
    country: 'США',
  },
  '4KB': { make: 'Chevrolet', manufacturer: 'Chevrolet W-Series incomplete vehicle', country: 'США' },
  '4KD': { make: 'GMC', manufacturer: 'GMC W-Series incomplete vehicle', country: 'США' },
  '4KL': { make: 'Isuzu', manufacturer: 'Isuzu commercial truck built by GM', country: 'США' },
  '4M2': { make: 'Mercury', manufacturer: 'Mercury MPV/SUV', country: 'США' },
  '4N2': { make: 'Nissan', manufacturer: 'Nissan Quest made by Ford', country: 'США' },
  '4NU': { make: 'Isuzu', manufacturer: 'Isuzu Ascender made by GM', country: 'США' },
  '4P3': {
    make: 'Plymouth',
    manufacturer: 'Plymouth car made by Diamond-Star Motors factory 1990–1994',
    country: 'США',
  },
  '4S1': { make: 'Isuzu', manufacturer: 'Isuzu truck made by Subaru Isuzu Automotive', country: 'США' },
  '4S2': { make: 'Isuzu', manufacturer: 'Isuzu SUV made by Subaru Isuzu Automotive', country: 'США' },
  '4S3': { make: 'Subaru', manufacturer: 'Subaru car', country: 'США' },
  '4S4': { make: 'Subaru', manufacturer: 'Subaru SUV/MPV', country: 'США' },
  '4S6': { make: 'Honda', manufacturer: 'Honda SUV made by Subaru Isuzu Automotive', country: 'США' },
  '4T1': { make: 'Toyota', manufacturer: 'Toyota Motor Manufacturing Kentucky (Camry)', country: 'США' },
  '4T3': { make: 'Toyota', manufacturer: 'Toyota MPV/SUV made by Toyota Motor Manufacturing Kentucky', country: 'США' },
  '4T4': { make: 'Toyota', manufacturer: 'Toyota car made by Subaru of Indiana Automotive', country: 'США' },
  '4TA': { make: 'Toyota', manufacturer: 'Toyota truck made by NUMMI', country: 'США' },
  '4US': { make: 'BMW', manufacturer: 'BMW Manufacturing, Спартанберг (X5, X3)', country: 'США' },
  '4UZ': {
    make: 'Freightliner',
    manufacturer: 'Freightliner Custom Chassis Corporation & gas-powered Mitsubishi Fuso trucks ass',
    country: 'США',
  },
  '4V4': { make: 'Volvo', manufacturer: 'Volvo Trucks North America truck', country: 'США' },
  '4V5': { make: 'Volvo', manufacturer: 'Volvo Trucks North America incomplete vehicle', country: 'США' },
  '50E': { make: 'Lucid', manufacturer: 'Lucid Motors', country: 'США' },
  '54D': {
    make: 'Isuzu',
    manufacturer: 'Isuzu & Chevrolet commercial trucks built by Spartan Motors/The Shyft Group',
    country: 'США',
  },
  '55S': { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz U.S. International', country: 'США' },
  '58A': { make: 'Lexus', manufacturer: 'Toyota Motor Manufacturing Kentucky (Lexus ES)', country: 'США' },
  '5BZ': { make: 'Nissan', manufacturer: 'Nissan "bus"', country: 'США' },
  '5FN': { make: 'Honda', manufacturer: 'Honda MPV/SUV made by Honda Manufacturing of Alabama', country: 'США' },
  '5FP': { make: 'Honda', manufacturer: 'Honda truck made by Honda Manufacturing of Alabama', country: 'США' },
  '5FR': { make: 'Acura', manufacturer: 'Acura SUV made by Honda Manufacturing of Alabama', country: 'США' },
  '5G8': { make: 'Holden', manufacturer: 'Holden Volt', country: 'США' },
  '5GA': { make: 'Buick', manufacturer: 'Buick MPV/SUV', country: 'США' },
  '5GD': { make: 'Daewoo', manufacturer: 'Daewoo G2X', country: 'США' },
  '5GN': { make: 'Hummer', manufacturer: 'Hummer H3T', country: 'США' },
  '5GR': { make: 'Hummer', manufacturer: 'Hummer H2', country: 'США' },
  '5GT': { make: 'Hummer', manufacturer: 'Hummer H3', country: 'США' },
  '5GZ': { make: 'Saturn', manufacturer: 'Saturn MPV/SUV', country: 'США' },
  '5J6': { make: 'Honda', manufacturer: 'Honda SUV made by Honda of America Mfg. in Ohio', country: 'США' },
  '5J8': { make: 'Acura', manufacturer: 'Acura SUV made by Honda of America Mfg. in Ohio', country: 'США' },
  '5KB': { make: 'Honda', manufacturer: 'Honda car made by Honda Manufacturing of Alabama', country: 'США' },
  '5L1': { make: 'Lincoln', manufacturer: 'Lincoln SUV', country: 'США' },
  '5LD': { make: 'Ford', manufacturer: 'Ford & Lincoln incomplete vehicle – limousine', country: 'США' },
  '5LM': { make: 'Lincoln', manufacturer: 'Lincoln SUV', country: 'США' },
  '5LT': { make: 'Lincoln', manufacturer: 'Lincoln truck', country: 'США' },
  '5N1': { make: 'Nissan', manufacturer: 'Nissan North America (SUV)', country: 'США' },
  '5N3': { make: 'Infiniti', manufacturer: 'Infiniti SUV', country: 'США' },
  '5NM': { make: 'Hyundai', manufacturer: 'Hyundai Motor Manufacturing Alabama (Santa Fe, Tucson)', country: 'США' },
  '5NP': { make: 'Hyundai', manufacturer: 'Hyundai Motor Manufacturing Alabama (Sonata, Elantra)', country: 'США' },
  '5NT': { make: 'Hyundai', manufacturer: 'Hyundai truck', country: 'США' },
  '5PV': { make: 'Hino', manufacturer: 'Hino incomplete vehicle', country: 'США' },
  '5S3': { make: 'Saab', manufacturer: 'Saab 9-7X', country: 'США' },
  '5TB': { make: 'Toyota', manufacturer: 'Toyota truck made by TMMI', country: 'США' },
  '5TD': { make: 'Toyota', manufacturer: 'Toyota Motor Manufacturing Indiana (Highlander, Sienna)', country: 'США' },
  '5TE': { make: 'Toyota', manufacturer: 'Toyota truck made by NUMMI', country: 'США' },
  '5TF': { make: 'Toyota', manufacturer: 'Toyota truck made by TMMTX', country: 'США' },
  '5UM': { make: 'BMW', manufacturer: 'BMW M car', country: 'США' },
  '5UX': { make: 'BMW', manufacturer: 'BMW Manufacturing, Спартанберг (X3, X5, X7)', country: 'США' },
  '5XX': { make: 'Kia', manufacturer: 'Kia Georgia (Optima/K5)', country: 'США' },
  '5XY': { make: 'Kia', manufacturer: 'Kia Georgia (Sorento, Telluride)', country: 'США' },
  '5Y2': { make: 'Pontiac', manufacturer: 'Pontiac Vibe made by NUMMI', country: 'США' },
  '5YF': { make: 'Toyota', manufacturer: 'Toyota car made by TMMMS', country: 'США' },
  '5YJ': { make: 'Tesla', manufacturer: 'Tesla, Фримонт', country: 'США' },
  '5YM': { make: 'BMW', manufacturer: 'BMW M SUV', country: 'США' },
  '5Z6': { make: 'Suzuki', manufacturer: 'Suzuki truck made by Nissan', country: 'США' },
  '6F1': { make: 'Ford', manufacturer: 'Ford', country: 'Австралия' },
  '6F2': { make: 'Iveco', manufacturer: 'Iveco Trucks Australia Ltd.', country: 'Австралия' },
  '6F4': { make: 'Nissan', manufacturer: 'Nissan Motor Australia', country: 'Австралия' },
  '6F5': { make: 'Kenworth', manufacturer: 'Kenworth Australia', country: 'Австралия' },
  '6FM': { make: 'Mack', manufacturer: 'Mack Trucks Australia', country: 'Австралия' },
  '6FP': { make: 'Ford', manufacturer: 'Ford', country: 'Австралия' },
  '6G1': { make: 'Holden', manufacturer: 'Holden & Chevrolet', country: 'Австралия' },
  '6G2': { make: 'Pontiac', manufacturer: 'Pontiac', country: 'Австралия' },
  '6G3': { make: 'Chevrolet', manufacturer: 'Chevrolet', country: 'Австралия' },
  '6MM': { make: 'Mitsubishi', manufacturer: 'Mitsubishi', country: 'Австралия' },
  '6MP': { make: 'Mercury', manufacturer: 'Mercury Capri', country: 'Австралия' },
  '6T1': { make: 'Toyota', manufacturer: 'Toyota', country: 'Австралия' },
  '7A1': { make: 'Mitsubishi', manufacturer: 'Mitsubishi', country: 'Новая Зеландия' },
  '7A3': { make: 'Honda', manufacturer: 'Honda', country: 'Новая Зеландия' },
  '7A4': { make: 'Toyota', manufacturer: 'Toyota', country: 'Новая Зеландия' },
  '7A5': { make: 'Ford', manufacturer: 'Ford', country: 'Новая Зеландия' },
  '7A7': { make: 'Nissan', manufacturer: 'Nissan New Zealand', country: 'Новая Зеландия' },
  '7FA': { make: 'Honda', manufacturer: 'Honda SUV made by Honda Manufacturing of Indiana', country: 'США' },
  '7FC': { make: 'Rivian', manufacturer: 'Rivian truck', country: 'США' },
  '7G2': { make: 'Tesla', manufacturer: 'Tesla Cybertruck & Tesla Semi', country: 'США' },
  '7GZ': { make: 'GMC', manufacturer: 'GMC incomplete vehicles made by Navistar International', country: 'США' },
  '7H4': { make: 'Hino', manufacturer: 'Hino truck', country: 'США' },
  '7JR': { make: 'Volvo', manufacturer: 'Volvo Cars car', country: 'США' },
  '7MM': { make: 'Mazda', manufacturer: 'Mazda SUV made by MTMUS', country: 'США' },
  '7MU': { make: 'Toyota', manufacturer: 'Toyota SUV made by MTMUS', country: 'США' },
  '7NA': { make: 'International', manufacturer: 'Navistar Defense', country: 'США' },
  '7PD': { make: 'Rivian', manufacturer: 'Rivian SUV', country: 'США' },
  '7SA': { make: 'Tesla', manufacturer: 'Tesla, Остин', country: 'США' },
  '7SV': { make: 'Toyota', manufacturer: 'Toyota SUV made by TMMTX', country: 'США' },
  '8A1': { make: 'Renault', manufacturer: 'Renault Argentina', country: 'Аргентина' },
  '8A3': { make: 'Scania', manufacturer: 'Scania Argentina', country: 'Аргентина' },
  '8AC': { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz vans', country: 'Аргентина' },
  '8AD': { make: 'Peugeot', manufacturer: 'Peugeot', country: 'Аргентина' },
  '8AE': { make: 'Peugeot', manufacturer: 'Peugeot van', country: 'Аргентина' },
  '8AF': { make: 'Ford', manufacturer: 'Ford Motor Argentina', country: 'Аргентина' },
  '8AG': { make: 'Chevrolet', manufacturer: 'General Motors de Argentina Chevrolet', country: 'Аргентина' },
  '8AJ': { make: 'Toyota', manufacturer: 'Toyota Argentina', country: 'Аргентина' },
  '8AN': { make: 'Nissan', manufacturer: 'Nissan', country: 'Аргентина' },
  '8AP': { make: 'Fiat', manufacturer: 'Fiat', country: 'Аргентина' },
  '8AT': { make: 'Iveco', manufacturer: 'Iveco', country: 'Аргентина' },
  '8AW': { make: 'Volkswagen', manufacturer: 'Volkswagen Argentina', country: 'Аргентина' },
  '8BC': { make: 'Citroën', manufacturer: 'Citroën', country: 'Аргентина' },
  '8BN': { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz incomplete vehicle', country: 'Аргентина' },
  '8BR': { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz "bus"', country: 'Аргентина' },
  '8BT': { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz MPV', country: 'Аргентина' },
  '8BU': { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz truck', country: 'Аргентина' },
  '8C3': { make: 'Honda', manufacturer: 'Honda car/SUV', country: 'Аргентина' },
  '8G1': { make: 'Renault', manufacturer: 'Automotores Franco Chilena S.A Renault', country: 'Чили' },
  '8GD': { make: 'Peugeot', manufacturer: 'Automotores Franco Chilena S.A Peugeot', country: 'Чили' },
  '8L4': {
    make: 'Great Wall',
    manufacturer: 'Great Wall Motors made by Ciudad del Auto Ciauto Cia. Ltda.',
    country: 'Эквадор',
  },
  '8LF': { make: 'Mazda', manufacturer: 'Maresa', country: 'Эквадор' },
  '8LG': { make: 'Hyundai', manufacturer: 'Aymesa', country: 'Эквадор' },
  '8XD': { make: 'Ford', manufacturer: 'Ford Motor Venezuela', country: 'Венесуэла' },
  '8XJ': { make: 'Mack', manufacturer: 'Mack de Venezuela C.A.', country: 'Венесуэла' },
  '8XV': { make: 'Iveco', manufacturer: 'Iveco Venezuela C.A.', country: 'Венесуэла' },
  '92V': { make: 'BYD', manufacturer: 'BYD Cars assembled in Camaçari - Bahia' },
  '92Z': { make: 'Great Wall', manufacturer: 'Great Wall Motors' },
  '935': { make: 'Citroën', manufacturer: 'Citroën', country: 'Бразилия' },
  '936': { make: 'Peugeot', manufacturer: 'Peugeot', country: 'Бразилия' },
  '937': { make: 'Dodge', manufacturer: 'Dodge', country: 'Бразилия' },
  '93C': { make: 'Chevrolet', manufacturer: 'General Motors do Brasil Chevrolet SUV', country: 'Бразилия' },
  '93H': { make: 'Honda', manufacturer: 'Honda car/SUV', country: 'Бразилия' },
  '93K': { make: 'Volvo', manufacturer: 'Volvo Trucks', country: 'Бразилия' },
  '93S': { make: 'International', manufacturer: 'Navistar International', country: 'Бразилия' },
  '93U': { make: 'Audi', manufacturer: 'Audi 1999–2006', country: 'Бразилия' },
  '93V': { make: 'International', manufacturer: 'Navistar International', country: 'Бразилия' },
  '93W': { make: 'Fiat', manufacturer: 'Fiat Ducato made by Iveco 2000–2016', country: 'Бразилия' },
  '93X': { make: 'Mitsubishi', manufacturer: 'Souza Ramos – Mitsubishi Motors / Suzuki Jimny', country: 'Бразилия' },
  '93Y': { make: 'Renault', manufacturer: 'Renault do Brasil', country: 'Бразилия' },
  '93Z': { make: 'Iveco', manufacturer: 'Iveco', country: 'Бразилия' },
  '94D': { make: 'Nissan', manufacturer: 'Nissan', country: 'Бразилия' },
  '953': { make: 'Volkswagen', manufacturer: 'VW Truck & Bus / MAN Truck & Bus', country: 'Бразилия' },
  '95P': { make: 'Hyundai', manufacturer: 'CAOA / Hyundai, Chery, Changan', country: 'Бразилия' },
  '988': { make: 'Jeep', manufacturer: 'Jeep and Fiat', country: 'Бразилия' },
  '98M': { make: 'BMW', manufacturer: 'BMW car/SUV', country: 'Бразилия' },
  '98R': { make: 'Chery', manufacturer: 'Chery', country: 'Бразилия' },
  '99A': { make: 'Audi', manufacturer: 'Audi 2016-', country: 'Бразилия' },
  '99J': { make: 'Jaguar', manufacturer: 'Jaguar Land Rover', country: 'Бразилия' },
  '99L': { make: 'BYD', manufacturer: 'BYD Bus chassis assembled in Campinas - São Paulo', country: 'Бразилия' },
  '9BD': { make: 'Fiat', manufacturer: 'Fiat Automóveis', country: 'Бразилия' },
  '9BF': { make: 'Ford', manufacturer: 'Ford Brasil', country: 'Бразилия' },
  '9BG': { make: 'Chevrolet', manufacturer: 'General Motors do Brasil Chevrolet', country: 'Бразилия' },
  '9BH': { make: 'Hyundai', manufacturer: 'Hyundai Motor Brasil', country: 'Бразилия' },
  '9BM': { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz car & SUV & commercial truck', country: 'Бразилия' },
  '9BR': { make: 'Toyota', manufacturer: 'Toyota', country: 'Бразилия' },
  '9BS': { make: 'Scania', manufacturer: 'Scania Brazil', country: 'Бразилия' },
  '9BV': { make: 'Volvo', manufacturer: 'Volvo Trucks', country: 'Бразилия' },
  '9BW': { make: 'Volkswagen', manufacturer: 'Volkswagen do Brasil', country: 'Бразилия' },
  '9DW': {
    make: 'Kenworth',
    manufacturer: 'Kenworth & Peterbilt trucks made by Volkswagen do Brasil',
    country: 'Бразилия',
  },
  '9FB': { make: 'Renault', manufacturer: 'Sofasa', country: 'Колумбия' },
  '9FC': { make: 'Mazda', manufacturer: 'Compañía Colombiana Automotriz S.A.', country: 'Колумбия' },
  '9GA': { make: 'Chevrolet', manufacturer: 'GM Colmotores S.A.', country: 'Колумбия' },
  '9UJ': { make: 'Chery', manufacturer: 'Chery assembled by Chery Socma S.A.', country: 'Уругвай' },
  '9UK': { make: 'Lifan', manufacturer: 'Lifan', country: 'Уругвай' },
  '9UW': { make: 'Kia', manufacturer: 'Kia made by Nordex S.A.', country: 'Уругвай' },
  '9V7': { make: 'Citroën', manufacturer: 'Citroen made by Nordex S.A.', country: 'Уругвай' },
  '9V8': { make: 'Peugeot', manufacturer: 'Peugeot made by Nordex S.A.', country: 'Уругвай' },
  AAA: { make: 'Audi', manufacturer: 'Audi South Africa made by Volkswagen of South Africa', country: 'ЮАР' },
  AAK: { make: 'FAW', manufacturer: 'FAW Vehicle Manufacturers SA Ltd.', country: 'ЮАР' },
  AAM: { make: 'MAN', manufacturer: 'MAN Automotive Ltd. includes VW Truck & Bus', country: 'ЮАР' },
  AAV: { make: 'Volkswagen', manufacturer: 'Volkswagen of South Africa', country: 'ЮАР' },
  ABJ: {
    make: 'Mitsubishi',
    manufacturer: 'Mitsubishi Colt & Triton pickups made by Mercedes-Benz South Africa 1994–2011',
    country: 'ЮАР',
  },
  ABM: { make: 'BMW', manufacturer: 'BMW Southern Africa', country: 'ЮАР' },
  AC5: { make: 'Hyundai', manufacturer: 'Hyundai Automotive South Africa', country: 'ЮАР' },
  ACV: { make: 'Isuzu', manufacturer: 'Isuzu Motors South Africa 2018-', country: 'ЮАР' },
  ADM: { make: 'Isuzu', manufacturer: 'General Motors South Africa includes Isuzu through 2018', country: 'ЮАР' },
  ADN: { make: 'Nissan', manufacturer: 'Nissan South Africa Ltd', country: 'ЮАР' },
  ADR: { make: 'Renault', manufacturer: 'Renault Sandero made by Nissan South Africa Ltd', country: 'ЮАР' },
  ADX: { make: 'Tata', manufacturer: 'Tata Automobile Corporation Ltd.', country: 'ЮАР' },
  AFA: { make: 'Ford', manufacturer: 'Ford Motor Company of Southern Africa & Samcor', country: 'ЮАР' },
  AFB: { make: 'Mazda', manufacturer: 'Mazda BT-50 made by Ford Motor Company of Southern Africa', country: 'ЮАР' },
  AHH: { make: 'Hino', manufacturer: 'Hino South Africa', country: 'ЮАР' },
  AHM: { make: 'Honda', manufacturer: 'Honda Ballade made by Mercedes-Benz South Africa 1982–2000', country: 'ЮАР' },
  AHT: { make: 'Toyota', manufacturer: 'Toyota South Africa Motors', country: 'ЮАР' },
  BAB: { make: 'BMW', manufacturer: 'BMW cars 1986-2019', country: 'Ангола' },
  BRY: { make: 'Fiat', manufacturer: 'Fiat el Djazaïr', country: 'Танзания' },
  DAA: { make: 'Fiat', manufacturer: 'Fiat Auto Egypt Industrial Co', country: 'Египет' },
  DAB: { make: 'BMW', manufacturer: 'BMW Egypt SKD', country: 'Египет' },
  GA1: { make: 'Renault', manufacturer: 'Renault /SOMACOA - Société Malgache de Construction Automobile' },
};

/**
 * Семейства по двум первым символам — когда точного WMI в таблице нет, но по
 * стандарту вся пара закреплена за одним производителем (JT — Toyota, WV —
 * Volkswagen). Смотрится ПОСЛЕ точной таблицы. make: null — производитель
 * многобрендовый (GM), тогда даём только завод.
 */
export const WMI_PREFIX_TABLE: Readonly<Record<string, WmiEntry>> = {
  JT: { make: 'Toyota', manufacturer: 'Toyota Motor', country: 'Япония' },
  JN: { make: 'Nissan', manufacturer: 'Nissan Motor', country: 'Япония' },
  JS: { make: 'Suzuki', manufacturer: 'Suzuki Motor', country: 'Япония' },
  JH: { make: 'Honda', manufacturer: 'Honda Motor', country: 'Япония' },
  JF: { make: 'Subaru', manufacturer: 'Subaru (Fuji Heavy Industries)', country: 'Япония' },
  JD: { make: 'Daihatsu', manufacturer: 'Daihatsu Motor', country: 'Япония' },
  JM: { make: 'Mazda', manufacturer: 'Mazda Motor', country: 'Япония' },
  KN: { make: 'Kia', manufacturer: 'Kia', country: 'Южная Корея' },
  KM: { make: 'Hyundai', manufacturer: 'Hyundai Motor', country: 'Южная Корея' },
  KL: { make: 'Chevrolet', manufacturer: 'GM Korea (Daewoo)', country: 'Южная Корея' },
  WV: { make: 'Volkswagen', manufacturer: 'Volkswagen', country: 'Германия' },
  WA: { make: 'Audi', manufacturer: 'Audi', country: 'Германия' },
  WB: { make: 'BMW', manufacturer: 'BMW', country: 'Германия' },
  WD: { make: 'Mercedes-Benz', manufacturer: 'Mercedes-Benz', country: 'Германия' },
  WP: { make: 'Porsche', manufacturer: 'Porsche', country: 'Германия' },
  W0: { make: 'Opel', manufacturer: 'Opel', country: 'Германия' },
  YV: { make: 'Volvo', manufacturer: 'Volvo', country: 'Швеция' },
  '1F': { make: 'Ford', manufacturer: 'Ford Motor Company', country: 'США' },
  '2F': { make: 'Ford', manufacturer: 'Ford of Canada', country: 'Канада' },
  '3F': { make: 'Ford', manufacturer: 'Ford de México', country: 'Мексика' },
  '1G': { make: null, manufacturer: 'General Motors (Chevrolet, Cadillac, Buick, GMC)', country: 'США' },
  '2G': { make: null, manufacturer: 'General Motors of Canada', country: 'Канада' },
  '3G': { make: null, manufacturer: 'General Motors de México', country: 'Мексика' },
  '1H': { make: 'Honda', manufacturer: 'Honda of America', country: 'США' },
  '1N': { make: 'Nissan', manufacturer: 'Nissan North America', country: 'США' },
  '3N': { make: 'Nissan', manufacturer: 'Nissan Mexicana', country: 'Мексика' },
  '2T': { make: 'Toyota', manufacturer: 'Toyota Motor Manufacturing Canada', country: 'Канада' },
  '4T': { make: 'Toyota', manufacturer: 'Toyota Motor Manufacturing (США)', country: 'США' },
  '5T': { make: 'Toyota', manufacturer: 'Toyota Motor Manufacturing (США)', country: 'США' },
  XT: { make: null, manufacturer: 'Бывший СССР (Россия и др.)', country: 'Россия' },
};

/** Марка/завод по VIN: точный WMI (3 символа), затем семейство по двум. null — не знаем. */
export function lookupWmi(vin: string): WmiEntry | null {
  const upper = (vin || '').toUpperCase();
  if (upper.length < 3) return null;
  return WMI_TABLE[upper.slice(0, 3)] ?? WMI_PREFIX_TABLE[upper.slice(0, 2)] ?? null;
}
